// The installed packages' smoke suite. checks/package.js copies it into fresh
// Node.js and Deno projects that installed @necessary/pgorm from a registry
// serving only the packed tarballs, and runs it there under `node --test` and
// `deno test` against the server PGORM_TEST_DSN names. It imports the package
// by name, as an application does: Node.js resolves it from node_modules, and
// Deno as `npm:@necessary/pgorm` through the project's import map.
//
// The check passes the package version and the platform package it expects
// the addon to come from in PGORM_NAPI_VERSION and PGORM_NAPI_PLATFORM_PACKAGE.
// Each run works in a schema of its own, named for the runtime and process,
// dropped when it ends.

import assert from "node:assert/strict";
import { spawn } from "node:child_process";
import { existsSync, readFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import process from "node:process";
import { after, before, test } from "node:test";
import { fileURLToPath } from "node:url";

import { col, column, connect, Decimal, insert, model, Pool, select, Table, version } from "@necessary/pgorm";

const dsn = required("PGORM_TEST_DSN");
const expectedVersion = required("PGORM_NAPI_VERSION");
const platformPackage = required("PGORM_NAPI_PLATFORM_PACKAGE");
const deno = "Deno" in globalThis;
const schema = `pgorm_napi_smoke_${deno ? "deno" : "node"}_${process.pid}`;

function required(name: string): string {
  const value = process.env[name];
  if (!value) throw new Error(`${name} is not set: checks/package.js runs this suite`);
  return value;
}

async function maintenance(sql: string): Promise<void> {
  await using pool = new Pool(dsn, { maxSize: 1 });
  await pool.execute(sql);
}

before(async () => {
  await maintenance(`DROP SCHEMA IF EXISTS ${schema} CASCADE`);
  await maintenance(`CREATE SCHEMA ${schema}`);
  await maintenance(
    `CREATE TABLE ${schema}.account (
       id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       name text NOT NULL,
       balance numeric NOT NULL DEFAULT 0
     )`,
  );
});

after(async () => {
  await maintenance(`DROP SCHEMA IF EXISTS ${schema} CASCADE`);
});

/** The installed main package's module, and the require that module loads its addon with. */
const entry = fileURLToPath(import.meta.resolve("@necessary/pgorm"));
const mainRequire = createRequire(entry);
const mainDirectory = dirname(dirname(entry));
const platformDirectory = dirname(mainRequire.resolve(`${platformPackage}/package.json`));

function readJson(path: string): Record<string, unknown> {
  return JSON.parse(readFileSync(path, "utf8"));
}

// [spec:pgorm:req:napi.packages+1/test]
// [spec:pgorm:req:napi.platform-loading/test]
test("the installed module loads its addon from the platform package", () => {
  assert.equal(version, expectedVersion);
  assert.equal(existsSync(join(dirname(entry), "pgorm_napi.node")), false, "the main package carries an addon");
  assert.equal(mainRequire.resolve(platformPackage), join(platformDirectory, "pgorm_napi.node"));
});

// [spec:pgorm:req:napi.release-builds/test]
test("the installed addon is a release build of this version", () => {
  const addon = mainRequire(platformPackage);
  assert.equal(addon.version, expectedVersion);
  assert.equal(addon.probePanic, undefined);
  assert.equal(addon.probeDropQueue, undefined);
});

// [spec:pgorm:req:napi.packages+1/test]
// [spec:pgorm:req:napi.support/test]
test("the main package offers the release platforms' packages at its own version", () => {
  const main = readJson(join(mainDirectory, "package.json"));
  const support = readJson(join(mainDirectory, "support.json")) as {
    platforms: { package: string; release: boolean }[];
  };
  const releases = support.platforms.filter((entry) => entry.release).map((entry) => entry.package);
  const offered = main.optionalDependencies as Record<string, string>;
  for (const [name, range] of Object.entries(offered)) {
    assert.ok(releases.includes(name), `${name} is offered but support.json builds no release of it`);
    assert.equal(range, expectedVersion);
  }
  if (process.env.PGORM_NAPI_PARTIAL !== "1") assert.deepEqual(Object.keys(offered).sort(), releases.sort());
  assert.ok(platformPackage in offered);
  const platform = readJson(join(platformDirectory, "package.json"));
  assert.equal(platform.version, expectedVersion);
  assert.equal(main.name, "@necessary/pgorm");
  assert.equal(platform.name, platformPackage);
  assert.ok(platformPackage.startsWith("@necessary/pgorm-"), platformPackage);
  for (const manifest of [main, platform]) assert.deepEqual(manifest.publishConfig, { access: "public" }, `${manifest.name}`);
});

// [spec:pgorm:req:napi.notices/test]
test("the platform package carries the dependency notices and the licences", () => {
  const inventory = readJson(join(platformDirectory, "DEPENDENCIES.json")) as { packages: { name: string; license: string }[] };
  const names = inventory.packages.map((entry) => entry.name);
  for (const name of ["pgorm", "pgorm-napi", "neon", "tokio-postgres", "rustls"]) assert.ok(names.includes(name), name);
  assert.ok(inventory.packages.every((entry) => entry.license), "a package without a licence");
  assert.match(readFileSync(join(platformDirectory, "THIRD_PARTY_NOTICES.txt"), "utf8"), /^@necessary\/pgorm npm packages/);
  for (const directory of [mainDirectory, platformDirectory]) {
    for (const licence of ["LICENSE-MIT", "LICENSE-APACHE"]) assert.ok(existsSync(join(directory, licence)), `${directory} lacks ${licence}`);
  }
});

// [spec:pgorm:req:napi.distribution/test]
test("connects and runs a bound query", async () => {
  await using pool = await connect(dsn);
  const row = await pool.one("SELECT $1::int8 + 1 AS n, current_setting('server_version_num')::int4 AS server", [41n]);
  assert.equal(row.n, 42n);
  assert.ok(Number(row.server) >= 180000, `PostgreSQL ${row.server} is older than 18`);
});

// [spec:pgorm:req:napi.distribution/test]
test("Temporal, bigint and Decimal values round-trip", async () => {
  await using pool = new Pool(dsn);
  const at = Temporal.Instant.from("2026-10-09T12:34:56.123456Z");
  const day = Temporal.PlainDate.from("2026-10-09");
  const big = 9_007_199_254_740_993n;
  const amount = new Decimal("19.9900");
  const row = await pool.one(
    "SELECT $1::timestamptz AS at, $2::date AS day, $3::int8 AS big, $4::numeric AS amount",
    [at, day, big, amount],
  );
  assert.ok(row.at instanceof Temporal.Instant && row.at.equals(at), `${row.at}`);
  assert.ok(row.day instanceof Temporal.PlainDate && row.day.equals(day), `${row.day}`);
  assert.equal(row.big, big);
  assert.ok(row.amount instanceof Decimal);
  assert.equal(String(row.amount), "19.9900");
});

// [spec:pgorm:req:napi.distribution/test]
test("a built statement writes and reads", async () => {
  await using pool = new Pool(dsn);
  const account = new Table("account", { schema });
  const [written] = await pool.query(
    insert(account).columns("name", "balance").values("Ann", new Decimal("10.50")).returning([col("id")]),
  );
  const id = written?.id;
  assert.ok(typeof id === "bigint", `id ${id}`);
  const read = await pool.one(select(col("name"), col("balance")).from(account).where(col("id").eq(id)));
  assert.equal(read.name, "Ann");
  assert.equal(String(read.balance), "10.50");
});

// [spec:pgorm:req:napi.distribution/test]
test("a model inserts and finds its records", async () => {
  await using pool = new Pool(dsn);
  const Account = model("account", {
    schema,
    columns: {
      id: column("i64", { primaryKey: true, generated: "byDefault" }),
      name: column("text"),
      balance: column("decimal", { default: true }),
    },
  });
  const bea = await Account.insert({ name: "Bea" }).returning().one(pool);
  assert.equal(typeof bea.id, "bigint");
  assert.equal(String(bea.balance), "0");
  const found = await Account.find().where(Account.col("name").eq("Bea")).one(pool);
  assert.equal(found.id, bea.id);
});

// [spec:pgorm:req:napi.distribution/test]
test("a transaction commits, and rolls back when its function throws", async () => {
  await using pool = new Pool(dsn);
  const count = async () => (await pool.one(`SELECT count(*) AS n FROM ${schema}.account WHERE name = 'Cy'`)).n;
  await pool.transaction(async (tx) => {
    await tx.execute(`INSERT INTO ${schema}.account (name) VALUES ($1)`, ["Cy"]);
  });
  assert.equal(await count(), 1n);
  const failure = new Error("roll back");
  await assert.rejects(
    pool.transaction(async (tx) => {
      await tx.execute(`INSERT INTO ${schema}.account (name) VALUES ($1)`, ["Cy"]);
      throw failure;
    }),
    (error) => error === failure,
  );
  assert.equal(await count(), 1n);
});

// [spec:pgorm:req:napi.distribution/test]
test("a process that used the package exits on its own", async () => {
  const script = fileURLToPath(new URL("./exit.ts", import.meta.url));
  const args = deno ? ["run", "--allow-ffi", "--allow-read", "--allow-env", script] : [script];
  const outcome = await new Promise<{ code: number | null; stdout: string; stderr: string; hung: boolean }>(
    (resolve, reject) => {
      const child = spawn(process.execPath, args, {
        env: { ...process.env, NO_COLOR: "1" },
        stdio: ["ignore", "pipe", "pipe"],
      });
      let stdout = "";
      let stderr = "";
      let hung = false;
      child.stdout.setEncoding("utf8").on("data", (chunk: string) => (stdout += chunk));
      child.stderr.setEncoding("utf8").on("data", (chunk: string) => (stderr += chunk));
      const timer = setTimeout(() => {
        hung = true;
        child.kill("SIGKILL");
      }, 30_000);
      child.on("error", (error) => {
        clearTimeout(timer);
        reject(error);
      });
      child.on("close", (code) => {
        clearTimeout(timer);
        resolve({ code, stdout, stderr, hung });
      });
    },
  );
  assert.equal(outcome.hung, false, `killed after 30 s without exiting:\n${outcome.stderr}`);
  assert.equal(outcome.stderr, "");
  assert.equal(outcome.code, 0);
  assert.equal(outcome.stdout, "settled 42\n");
});
