#![allow(unused_imports, dead_code)]

//! `GENERATED { ALWAYS | BY DEFAULT } AS IDENTITY` against a live PostgreSQL
//! server.
//!
//! The render tests in pgorm-query feed the SQL to the real grammar, which
//! settles that it parses — and the grammar accepts every combination here,
//! including the ones no server will run. What only a server settles is what
//! the clause *means*: that the column's values come from a sequence nobody
//! asked for, that `ALWAYS` refuses a value a statement supplies while
//! `BY DEFAULT` takes it, and that identity alongside a `DEFAULT` or a
//! `GENERATED ... STORED` expression is rejected outright. That last pair is
//! the reason the mutual exclusion is documented rather than typed, so it is
//! checked here rather than asserted in prose.

pub mod common;
pub use common::{TestContext, setup::*};
use pgorm::pgorm_query::{ColumnDef, Expr, Name, Overriding, Query, Table};
use pgorm::{ConnectionTrait, entity::prelude::*};

#[pgorm_macros::test]
async fn main() -> Result<(), Error> {
    let ctx = TestContext::new("identity_column_tests").await;
    let db = ctx.db.get().await?;

    identity_generates_values_without_being_asked(&db).await?;
    always_refuses_an_explicit_value(&db).await?;
    by_default_accepts_an_explicit_value(&db).await?;
    identity_excludes_default_and_generated(&db).await?;
    added_to_an_existing_column(&db).await?;

    drop(db);
    ctx.delete().await;

    Ok(())
}

/// The DDL a builder chain renders, run through the simple-query protocol.
async fn ddl(db: &DatabaseConnection, sql: String) -> Result<(), Error> {
    db.batch_execute(&sql).await
}

/// Both forms fill the column from their own sequence when the insert leaves it
/// out, and the values are the sequence's, not the type's zero.
// [spec:pgorm:req:sql.ddl.column-def+5/test]
async fn identity_generates_values_without_being_asked(
    db: &DatabaseConnection,
) -> Result<(), Error> {
    let always = Table::create(Name::runtime("id_always"))
        .col(
            ColumnDef::new(Name::runtime("id"))
                .integer()
                .identity()
                .primary_key(),
        )
        .col(ColumnDef::new(Name::runtime("label")).text().not_null())
        .to_string();
    assert_eq!(
        always,
        r#"CREATE TABLE "id_always" ( "id" integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY, "label" text NOT NULL )"#
    );
    ddl(db, always).await?;

    let by_default = Table::create(Name::runtime("id_by_default"))
        .col(
            ColumnDef::new(Name::runtime("id"))
                .big_integer()
                .identity_by_default()
                .primary_key(),
        )
        .col(ColumnDef::new(Name::runtime("label")).text().not_null())
        .to_string();
    assert_eq!(
        by_default,
        r#"CREATE TABLE "id_by_default" ( "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "label" text NOT NULL )"#
    );
    ddl(db, by_default).await?;

    db.batch_execute(
        "INSERT INTO id_always (label) VALUES ('a'), ('b');
         INSERT INTO id_by_default (label) VALUES ('a'), ('b');",
    )
    .await?;

    let ids: Vec<i32> = db
        .query_all("SELECT id FROM id_always ORDER BY id", &[])
        .await?
        .iter()
        .map(|r| r.get::<_, i32>(0))
        .collect();
    assert_eq!(ids, vec![1, 2]);

    let ids: Vec<i64> = db
        .query_all("SELECT id FROM id_by_default ORDER BY id", &[])
        .await?
        .iter()
        .map(|r| r.get::<_, i64>(0))
        .collect();
    assert_eq!(ids, vec![1, 2]);

    // The column really owns a sequence: the catalogue says so, and says which
    // form each was declared with.
    let generation: Vec<(String, String)> = db
        .query_all(
            "SELECT table_name::text, identity_generation::text
             FROM information_schema.columns
             WHERE table_name IN ('id_always', 'id_by_default') AND column_name = 'id'
             ORDER BY table_name",
            &[],
        )
        .await?
        .iter()
        .map(|r| (r.get::<_, String>(0), r.get::<_, String>(1)))
        .collect();
    assert_eq!(
        generation,
        vec![
            ("id_always".to_owned(), "ALWAYS".to_owned()),
            ("id_by_default".to_owned(), "BY DEFAULT".to_owned()),
        ]
    );

    Ok(())
}

/// The whole point of `ALWAYS`: a statement cannot hand the column a value.
// [spec:pgorm:req:sql.ddl.column-def+5/test]
async fn always_refuses_an_explicit_value(db: &DatabaseConnection) -> Result<(), Error> {
    let refused = db
        .execute("INSERT INTO id_always (id, label) VALUES (99, 'c')", &[])
        .await;
    let message = refused
        .expect_err("ALWAYS accepted an explicit value")
        .to_string();
    assert!(
        message.contains("cannot insert") || message.contains("identity"),
        "unexpected refusal: {message}"
    );

    // And the documented escape hatch still works, which is what makes the
    // refusal a policy rather than an impossibility — now spelled by the
    // builder rather than by the raw SQL this test needed before
    // `[spec:pgorm:def:sql.ast.insert+3]`.
    let sql = Query::insert()
        .into_table(Name::runtime("id_always"))
        .columns([Name::runtime("id"), Name::runtime("label")])
        .overriding(Overriding::SystemValue)
        .values_panic([99.into(), "c".into()])
        .to_string();
    db.execute(&sql, &[]).await?;
    let row = db
        .query_one("SELECT count(*) FROM id_always WHERE id = 99", &[])
        .await?;
    assert_eq!(row.get::<_, i64>(0), 1);

    Ok(())
}

/// The whole point of `BY DEFAULT`: the sequence fills in only where the
/// statement stays silent.
// [spec:pgorm:req:sql.ddl.column-def+5/test]
async fn by_default_accepts_an_explicit_value(db: &DatabaseConnection) -> Result<(), Error> {
    db.execute(
        "INSERT INTO id_by_default (id, label) VALUES (99, 'c')",
        &[],
    )
    .await?;

    let row = db
        .query_one("SELECT label FROM id_by_default WHERE id = 99", &[])
        .await?;
    assert_eq!(row.get::<_, String>(0), "c");

    Ok(())
}

/// The mutual exclusion the rule documents instead of typing: the grammar takes
/// each of these, the server does not. Both renders are built by the ordinary
/// fluent chain, so this is exactly what a caller who combined them would get.
// [spec:pgorm:req:sql.ddl.column-def+5/test]
async fn identity_excludes_default_and_generated(db: &DatabaseConnection) -> Result<(), Error> {
    let with_default = Table::create(Name::runtime("id_and_default"))
        .col(
            ColumnDef::new(Name::runtime("id"))
                .integer()
                .default(1i32)
                .identity(),
        )
        .to_string();
    assert_eq!(
        with_default,
        r#"CREATE TABLE "id_and_default" ( "id" integer DEFAULT 1 GENERATED ALWAYS AS IDENTITY )"#
    );
    let message = db
        .batch_execute(&with_default)
        .await
        .expect_err("DEFAULT alongside identity was accepted")
        .to_string();
    assert!(
        message.contains("default") && message.contains("identity"),
        "unexpected refusal: {message}"
    );

    let with_serial = Table::create(Name::runtime("id_and_serial"))
        .col(
            ColumnDef::new(Name::runtime("id"))
                .integer()
                .auto_increment()
                .identity(),
        )
        .to_string();
    assert_eq!(
        with_serial,
        r#"CREATE TABLE "id_and_serial" ( "id" serial GENERATED ALWAYS AS IDENTITY )"#
    );
    assert!(
        db.batch_execute(&with_serial).await.is_err(),
        "the serial family alongside identity was accepted"
    );

    let with_generated = Table::create(Name::runtime("id_and_generated"))
        .col(ColumnDef::new(Name::runtime("base")).integer().not_null())
        .col(
            ColumnDef::new(Name::runtime("id"))
                .integer()
                .generated(Expr::col(Name::runtime("base")).mul(2))
                .identity(),
        )
        .to_string();
    assert!(
        db.batch_execute(&with_generated).await.is_err(),
        "a generated expression alongside identity was accepted"
    );

    Ok(())
}

/// `ALTER TABLE` reaches identity from both sides: a new column carries the
/// clause, an existing one takes the `ADD GENERATED` action.
// [spec:pgorm:req:sql.ddl.column-def+5/test]
async fn added_to_an_existing_column(db: &DatabaseConnection) -> Result<(), Error> {
    ddl(
        db,
        Table::create(Name::runtime("id_later"))
            .col(ColumnDef::new(Name::runtime("id")).integer().not_null())
            .to_string(),
    )
    .await?;

    let altered = Table::alter(Name::runtime("id_later"))
        .modify_column(ColumnDef::new(Name::runtime("id")).identity_by_default())
        .to_string();
    assert_eq!(
        altered,
        r#"ALTER TABLE "id_later" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY"#
    );
    ddl(db, altered).await?;

    let added = Table::alter(Name::runtime("id_later"))
        .add_column(ColumnDef::new(Name::runtime("later")).integer().identity())
        .to_string();
    assert_eq!(
        added,
        r#"ALTER TABLE "id_later" ADD COLUMN "later" integer GENERATED ALWAYS AS IDENTITY"#
    );
    ddl(db, added).await?;

    db.execute("INSERT INTO id_later DEFAULT VALUES", &[])
        .await?;
    let row = db.query_one("SELECT id, later FROM id_later", &[]).await?;
    assert_eq!((row.get::<_, i32>(0), row.get::<_, i32>(1)), (1, 1));

    Ok(())
}
