#![allow(unused_imports, dead_code)]

//! `MERGE` against a live PostgreSQL server.
//!
//! The render tests in pgorm-query hold the spelling to libpg_query's
//! `MergeStmt`. Only a server settles what a statement does: which arm a row
//! takes when two conditional arms both hold, where an unconditional arm
//! still catches a row, that the condition on an arm narrows it, that `ONLY`
//! leaves an inheriting table's rows alone, that `OVERRIDING` reaches the
//! identity column it names, and that every bound value lands as data in the
//! column the server typed it by. Each case compares two statements, or a
//! statement and the state it should leave, so a clause that rendered and
//! was then ignored still fails.

pub mod common;
pub use common::{TestContext, setup::*};
use pgorm::pgorm_query::{
    CommonTableExpression, Expr, FromItem, Func, IntoNamedTable, IntoValueTuple, MatchedAction,
    MergeInsert, MergeStatement, MergeUpdate, Name, NotMatchedAction, Overriding, PendingMerge,
    Query, SimpleExpr, WithClause,
};
use pgorm::{ConnectionTrait, ValueHolder, entity::prelude::*};
use tokio_postgres::error::SqlState;

#[pgorm_macros::test]
async fn main() -> Result<(), Error> {
    let ctx = TestContext::new("merge_tests").await;
    let db = ctx.db.get().await?;

    db.batch_execute(
        "CREATE TABLE stock (\
             sku integer PRIMARY KEY, \
             name text NOT NULL, \
             qty integer NOT NULL, \
             serial integer GENERATED ALWAYS AS IDENTITY); \
         CREATE TABLE delivery (\
             sku integer NOT NULL, \
             name text NOT NULL, \
             qty integer NOT NULL, \
             retired boolean NOT NULL); \
         CREATE TABLE ledger (sku integer, note text); \
         CREATE TABLE ledger_archive () INHERITS (ledger); \
         CREATE TABLE tag (id integer GENERATED BY DEFAULT AS IDENTITY, label text); \
         CREATE TABLE tick (id integer GENERATED ALWAYS AS IDENTITY, note text DEFAULT 'fresh')",
    )
    .await?;

    a_merge_updates_deletes_and_inserts(&db).await?;
    conditional_arms_take_rows_in_call_order(&db).await?;
    unconditional_arm_takes_what_conditional_arms_left(&db).await?;
    every_value_is_bound_and_typed_by_column(&db).await?;
    only_leaves_an_inheriting_tables_rows_alone(&db).await?;
    overriding_reaches_the_identity_column(&db).await?;
    a_default_row_and_a_skipped_row(&db).await?;
    with_clause_and_other_sources_feed_merge(&db).await?;

    drop(db);
    ctx.delete().await;

    Ok(())
}

/// Reset both tables: three stocked items and three deliveries — one for a
/// stocked item, one retiring a stocked item, and one for a new item.
async fn reset(db: &DatabaseConnection) -> Result<(), Error> {
    db.batch_execute(
        "TRUNCATE stock RESTART IDENTITY; TRUNCATE delivery; \
         INSERT INTO stock (sku, name, qty) VALUES (1, 'one', 5), (2, 'two', 5), (3, 'three', 5); \
         INSERT INTO delivery VALUES (1, 'uno', 3, false), (2, 'dos', 0, true), \
             (4, 'cuatro', 7, false)",
    )
    .await
}

async fn stock(db: &DatabaseConnection) -> Result<Vec<(i32, String, i32)>, Error> {
    let rows = db
        .query_all("SELECT sku, name, qty FROM stock ORDER BY sku", &[])
        .await?;
    Ok(rows
        .iter()
        .map(|row| (row.get(0), row.get(1), row.get(2)))
        .collect())
}

/// Run `merge` the way a caller does: built, with its values bound.
async fn run(db: &DatabaseConnection, merge: &MergeStatement) -> Result<u64, Error> {
    let (sql, values) = merge.build();
    db.execute_raw(&sql, values.into_iter().map(ValueHolder))
        .await
}

fn stock_t() -> Name {
    Name::runtime("stock")
}

fn delivery_t() -> Name {
    Name::runtime("delivery")
}

fn stock_col(column: &'static str) -> Expr {
    Expr::col((stock_t(), Name::runtime(column)))
}

fn delivery_col(column: &'static str) -> Expr {
    Expr::col((delivery_t(), Name::runtime(column)))
}

fn retired() -> SimpleExpr {
    delivery_col("retired").into()
}

fn by_sku() -> PendingMerge {
    Query::merge(
        stock_t(),
        delivery_t(),
        stock_col("sku").equals((delivery_t(), Name::runtime("sku"))),
    )
}

fn restock() -> MergeUpdate {
    MergeUpdate::value(Name::runtime("name"), delivery_col("name")).and_value(
        Name::runtime("qty"),
        stock_col("qty").add(delivery_col("qty")),
    )
}

fn stock_new() -> MergeInsert {
    MergeInsert::value(Name::runtime("sku"), delivery_col("sku"))
        .and_value(Name::runtime("name"), delivery_col("name"))
        .and_value(Name::runtime("qty"), delivery_col("qty"))
}

fn owned(rows: &[(i32, &str, i32)]) -> Vec<(i32, String, i32)> {
    rows.iter()
        .map(|(sku, name, qty)| (*sku, (*name).to_owned(), *qty))
        .collect()
}

// [spec:pgorm:req:sql.ast.merge+1/test]    against a live server: the matched row is updated or
// deleted by its arm, the unmatched source row inserted, the untouched row left alone
// [spec:pgorm:req:sql.render.merge+1/test]
async fn a_merge_updates_deletes_and_inserts(db: &DatabaseConnection) -> Result<(), Error> {
    reset(db).await?;
    let merge = by_sku()
        .when_matched_and(retired(), MatchedAction::Delete)
        .when_matched(restock())
        .when_not_matched_and(retired().not(), stock_new())
        .to_owned();
    assert_eq!(run(db, &merge).await?, 3, "{merge}");
    assert_eq!(
        stock(db).await?,
        owned(&[(1, "uno", 8), (3, "three", 5), (4, "cuatro", 7)])
    );
    Ok(())
}

// [spec:pgorm:req:sql.ast.merge+1/test]    against a live server: when two conditional arms both
// hold, the row takes the one added first
async fn conditional_arms_take_rows_in_call_order(db: &DatabaseConnection) -> Result<(), Error> {
    let empty = || delivery_col("qty").eq(0);
    let any = || delivery_col("qty").gte(0);
    let zero = || MergeUpdate::value(Name::runtime("qty"), 0);

    reset(db).await?;
    let delete_first = by_sku()
        .when_matched_and(empty(), MatchedAction::Delete)
        .when_matched_and(any(), zero())
        .to_owned();
    run(db, &delete_first).await?;
    assert_eq!(
        stock(db).await?,
        owned(&[(1, "one", 0), (3, "three", 5)]),
        "{delete_first}"
    );

    reset(db).await?;
    let zero_first = by_sku()
        .when_matched_and(any(), zero())
        .when_matched_and(empty(), MatchedAction::Delete)
        .to_owned();
    run(db, &zero_first).await?;
    assert_eq!(
        stock(db).await?,
        owned(&[(1, "one", 0), (2, "two", 0), (3, "three", 5)]),
        "{zero_first}"
    );
    Ok(())
}

// [spec:pgorm:req:sql.ast.merge+1/test]    against a live server: an unconditional arm added
// first still renders where PostgreSQL accepts it, takes only the rows no conditional arm
// took, and the condition on the conditional arm narrows it
async fn unconditional_arm_takes_what_conditional_arms_left(
    db: &DatabaseConnection,
) -> Result<(), Error> {
    reset(db).await?;
    let merge = by_sku()
        .when_matched(restock())
        .when_matched_and(retired(), MatchedAction::DoNothing)
        .to_owned();
    assert_eq!(run(db, &merge).await?, 1, "{merge}");
    assert_eq!(
        stock(db).await?,
        owned(&[(1, "uno", 8), (2, "two", 5), (3, "three", 5)])
    );
    Ok(())
}

// [spec:pgorm:req:sql.render.merge+1/test]    against a live server: a value in the join
// condition, an arm's condition, an assignment and an inserted row is a parameter, stored
// verbatim in the column the server typed it by
async fn every_value_is_bound_and_typed_by_column(db: &DatabaseConnection) -> Result<(), Error> {
    reset(db).await?;
    let hostile = "it's'); DROP TABLE stock; --";
    let merge = Query::merge(
        stock_t(),
        delivery_t(),
        stock_col("sku")
            .equals((delivery_t(), Name::runtime("sku")))
            .and(delivery_col("qty").lt(100)),
    )
    .when_matched_and(
        stock_col("qty").eq(5),
        MergeUpdate::value(Name::runtime("name"), hostile).and_value(Name::runtime("qty"), 9),
    )
    .when_not_matched_and(
        delivery_col("name").eq("cuatro"),
        MergeInsert::value(Name::runtime("sku"), 40)
            .and_value(Name::runtime("name"), hostile)
            .and_value(Name::runtime("qty"), delivery_col("qty")),
    )
    .to_owned();
    let (sql, values) = merge.build();
    assert_eq!(values.0.len(), 7, "{sql}");
    assert!(!sql.contains("DROP TABLE"), "{sql}");
    assert_eq!(run(db, &merge).await?, 3, "{sql}");
    assert_eq!(
        stock(db).await?,
        owned(&[
            (1, hostile, 9),
            (2, hostile, 9),
            (3, "three", 5),
            (40, hostile, 7)
        ])
    );
    Ok(())
}

// [spec:pgorm:req:sql.ast.merge+1/test]    against a live server: ONLY writes the named table
// alone, and without it a child table's rows are matched too
async fn only_leaves_an_inheriting_tables_rows_alone(db: &DatabaseConnection) -> Result<(), Error> {
    let ledger = || Name::runtime("ledger");
    let merge = || {
        Query::merge(
            ledger(),
            delivery_t(),
            Expr::col((ledger(), Name::runtime("sku")))
                .equals((delivery_t(), Name::runtime("sku"))),
        )
        .when_matched(MergeUpdate::value(Name::runtime("note"), "seen"))
        .to_owned()
    };
    let notes = || async {
        let rows = db
            .query_all("SELECT note FROM ledger_archive ORDER BY sku", &[])
            .await?;
        Ok::<Vec<String>, Error>(rows.iter().map(|row| row.get(0)).collect())
    };

    reset(db).await?;
    db.batch_execute("TRUNCATE ledger; INSERT INTO ledger_archive VALUES (1, 'archived')")
        .await?;
    assert_eq!(run(db, merge().only()).await?, 0);
    assert_eq!(notes().await?, ["archived"]);

    assert_eq!(run(db, &merge()).await?, 1);
    assert_eq!(notes().await?, ["seen"]);
    Ok(())
}

// [spec:pgorm:req:sql.ast.merge+1/test]    against a live server: OVERRIDING SYSTEM VALUE writes
// an ALWAYS identity, which is refused without it, and OVERRIDING USER VALUE discards a
// value supplied for a BY DEFAULT one
async fn overriding_reaches_the_identity_column(db: &DatabaseConnection) -> Result<(), Error> {
    let insert_serial = |overriding: Option<Overriding>| {
        let insert = stock_new().and_value(Name::runtime("serial"), 100);
        let insert = match overriding {
            Some(overriding) => insert.overriding(overriding),
            None => insert,
        };
        by_sku().when_not_matched(insert).to_owned()
    };

    reset(db).await?;
    let refused = run(db, &insert_serial(None))
        .await
        .expect_err("an ALWAYS identity refuses a supplied value");
    match &refused {
        Error::Postgres(e) => assert_eq!(e.code(), Some(&SqlState::GENERATED_ALWAYS), "{e}"),
        other => panic!("expected Error::Postgres, got {other:?}"),
    }

    run(db, &insert_serial(Some(Overriding::SystemValue))).await?;
    let serial: i32 = db
        .query_one("SELECT serial FROM stock WHERE sku = 4", &[])
        .await?
        .get(0);
    assert_eq!(serial, 100);

    db.batch_execute("TRUNCATE tag RESTART IDENTITY").await?;
    let tag = Name::runtime("tag");
    let merge = Query::merge(
        tag.clone(),
        delivery_t(),
        Expr::col((tag, Name::runtime("label"))).equals((delivery_t(), Name::runtime("name"))),
    )
    .when_not_matched_and(
        delivery_col("sku").eq(4),
        MergeInsert::value(Name::runtime("id"), 500)
            .and_value(Name::runtime("label"), delivery_col("name"))
            .overriding(Overriding::UserValue),
    )
    .to_owned();
    run(db, &merge).await?;
    let id: i32 = db.query_one("SELECT id FROM tag", &[]).await?.get(0);
    assert_eq!(
        id, 1,
        "the supplied 500 is discarded for the sequence's value"
    );
    Ok(())
}

// [spec:pgorm:req:sql.ast.merge+1/test]    against a live server: INSERT DEFAULT VALUES writes a
// row of defaults, and DO NOTHING skips a source row. A value in a VALUES source is assigned to
// no column, so bound it has no type but `text` and the join refuses it (`42883`); written
// inline it is an integer literal
async fn a_default_row_and_a_skipped_row(db: &DatabaseConnection) -> Result<(), Error> {
    db.batch_execute("TRUNCATE tick RESTART IDENTITY").await?;
    let tick = Name::runtime("tick");
    let s = Name::runtime("s");
    let merge = Query::merge(
        tick.clone(),
        FromItem::ValuesList(
            vec![1i32.into_value_tuple(), 2i32.into_value_tuple()],
            s.clone(),
        ),
        Expr::col((tick, Name::runtime("id"))).equals((s.clone(), Name::runtime("column1"))),
    )
    .when_not_matched_and(
        Expr::col((s, Name::runtime("column1"))).eq(2),
        NotMatchedAction::DoNothing,
    )
    .when_not_matched(NotMatchedAction::InsertDefaultValues)
    .to_owned();
    let untyped = run(db, &merge)
        .await
        .expect_err("a bound VALUES row is text");
    match &untyped {
        Error::Postgres(e) => assert_eq!(e.code(), Some(&SqlState::UNDEFINED_FUNCTION), "{e}"),
        other => panic!("expected Error::Postgres, got {other:?}"),
    }
    assert_eq!(db.execute(&merge.to_string(), &[]).await?, 1, "{merge}");
    let rows = db.query_all("SELECT id, note FROM tick", &[]).await?;
    let rows: Vec<(i32, String)> = rows.iter().map(|row| (row.get(0), row.get(1))).collect();
    assert_eq!(rows, [(1, "fresh".to_owned())]);
    Ok(())
}

// [spec:pgorm:def:query.build.with+2/test]    against a live server: a WITH clause, here holding
// a data-modifying CTE, feeds the MERGE its source
// [spec:pgorm:req:sql.ast.merge+1/test]    a subquery and a function call as the source
async fn with_clause_and_other_sources_feed_merge(db: &DatabaseConnection) -> Result<(), Error> {
    reset(db).await?;
    let gone = Name::runtime("gone");
    let merge = Query::merge(
        stock_t(),
        gone.clone(),
        stock_col("sku").equals((gone.clone(), Name::runtime("sku"))),
    )
    .when_matched(MatchedAction::Delete)
    .with(WithClause::new(CommonTableExpression::new(
        gone,
        Query::delete()
            .from_table(delivery_t())
            .and_where(retired())
            .returning_all()
            .to_owned(),
    )))
    .to_owned();
    assert_eq!(run(db, &merge).await?, 1, "{merge}");
    assert_eq!(stock(db).await?, owned(&[(1, "one", 5), (3, "three", 5)]));
    let left: i64 = db
        .query_one("SELECT count(*) FROM delivery", &[])
        .await?
        .get(0);
    assert_eq!(left, 2, "the CTE's DELETE ran");

    let fresh = Name::runtime("fresh");
    let subquery = Query::merge(
        stock_t(),
        FromItem::SubQuery(
            Query::select()
                .columns([
                    Name::runtime("sku"),
                    Name::runtime("name"),
                    Name::runtime("qty"),
                ])
                .from(delivery_t())
                .and_where(delivery_col("qty").gt(5))
                .take(),
            fresh.clone(),
        ),
        stock_col("sku").equals((fresh.clone(), Name::runtime("sku"))),
    )
    .when_not_matched(
        MergeInsert::value(
            Name::runtime("sku"),
            Expr::col((fresh.clone(), Name::runtime("sku"))),
        )
        .and_value(
            Name::runtime("name"),
            Expr::col((fresh.clone(), Name::runtime("name"))),
        )
        .and_value(
            Name::runtime("qty"),
            Expr::col((fresh, Name::runtime("qty"))),
        ),
    )
    .to_owned();
    assert_eq!(run(db, &subquery).await?, 1, "{subquery}");

    let g = Name::runtime("g");
    let series = Query::merge(
        stock_t(),
        FromItem::FunctionCall(
            Func::named(Name::runtime("generate_series")).args([
                Expr::val(1).cast_as(Name::runtime("int4")),
                Expr::val(5).cast_as(Name::runtime("int4")),
            ]),
            g.clone(),
        ),
        stock_col("sku").equals((g.clone(), g.clone())),
    )
    .when_not_matched(
        MergeInsert::value(Name::runtime("sku"), Expr::col((g.clone(), g)))
            .and_value(Name::runtime("name"), "made")
            .and_value(Name::runtime("qty"), 0),
    )
    .to_owned();
    assert_eq!(run(db, &series).await?, 2, "{series}");
    assert_eq!(
        stock(db).await?,
        owned(&[
            (1, "one", 5),
            (2, "made", 0),
            (3, "three", 5),
            (4, "cuatro", 7),
            (5, "made", 0)
        ])
    );
    Ok(())
}
