from collections.abc import Iterator, Mapping
from typing import Any, Generic, Self, TypeVar
from .. import _native as native
from ..runtime import Connection
from ..transactions import Transaction

M = TypeVar("M", bound="ModelView[Any]")
A = TypeVar("A", bound="ActiveView[Any]")
Column = str | native.Identifier | native.EntityColumn

class ModelView(Mapping[str, Any], Generic[A]):
    _entity_name: str
    _active_class: type[A]
    def __init__(self, model: native.EntityModel) -> None: ...
    @property
    def native(self) -> native.EntityModel: ...
    @property
    def entity_name(self) -> str: ...
    def __getitem__(self, key: str) -> Any: ...
    def __iter__(self) -> Iterator[str]: ...
    def __len__(self) -> int: ...
    def tagged(self, key: str) -> native.Value: ...
    def with_value(self, column: Column, value: Any) -> Self: ...
    def into_active(self) -> A: ...

class ActiveView(Generic[M]):
    _entity_name: str
    _model_class: type[M]
    def __init__(self, active: native.ActiveModel) -> None: ...
    @property
    def native(self) -> native.ActiveModel: ...
    @property
    def entity_name(self) -> str: ...
    def get(self, column: Column) -> native.ActiveValue: ...
    def set(self, column: Column, value: Any) -> Self: ...
    def not_set(self, column: Column) -> Self: ...
    def reset(self, column: Column) -> Self: ...
    async def insert(self, connection: Connection | Transaction) -> M: ...
    async def update(self, connection: Connection | Transaction) -> M: ...
    async def delete(self, connection: Connection | Transaction) -> int: ...

class EntityView(Generic[M, A]):
    def __init__(
        self, entity: native.Entity, model: type[M], active: type[A]
    ) -> None: ...
    @property
    def name(self) -> str: ...
    def describe(self) -> dict[str, Any]: ...
    def col(self, name: str | native.Identifier) -> native.EntityColumn: ...
    def find(self) -> QueryView[M]: ...
    def active(self) -> A: ...

class QueryView(Generic[M]):
    def __init__(self, query: native.EntityQuery, model: type[M]) -> None: ...
    def filter(self, predicate: native.Expr | native.Condition) -> QueryView[M]: ...
    def order_by(self, *ordering: native.OrderBy) -> QueryView[M]: ...
    def limit(self, value: int | None = ...) -> QueryView[M]: ...
    def offset(self, value: int | None = ...) -> QueryView[M]: ...
    def inspect(self, *, terminal: str = ...) -> native.Compiled: ...
    async def all(self, connection: Connection | Transaction) -> list[M]: ...
    async def one(self, connection: Connection | Transaction) -> M: ...
    async def one_opt(self, connection: Connection | Transaction) -> M | None: ...
    def __bool__(self) -> bool: ...
