from typing import Any, Callable, Generic, TypeVar
from collections.abc import Sequence
from .. import _native as native
from ..runtime import Connection
from .entities import ModelView

R = TypeVar("R")

def wrap_row(
    row: Any, models: tuple[type[ModelView[Any]], ...], optional: tuple[bool, ...]
) -> Any: ...

class GraphView(Generic[R]):
    def __init__(self, graph: native.Graph, decode: Callable[..., R]) -> None: ...
    @property
    def name(self) -> str: ...
    def describe(self) -> dict[str, Any]: ...
    def find(self, *, aliases: Sequence[str] | None = ...) -> GraphQueryView[R]: ...

class GraphQueryView(Generic[R]):
    def __init__(self, query: native.GraphQuery, decode: Callable[..., R]) -> None: ...
    def col(self, source: int, column: str) -> native.Expr: ...
    def filter(
        self, predicate: native.Expr | native.Condition
    ) -> GraphQueryView[R]: ...
    def order_by(self, *ordering: native.OrderBy) -> GraphQueryView[R]: ...
    def inspect(self, *, terminal: str = ...) -> native.Compiled: ...
    def cursor(self, column: str) -> GraphCursorView[R]: ...
    async def all(self, connection: Connection) -> list[R]: ...
    async def one_opt(self, connection: Connection) -> R | None: ...
    def __bool__(self) -> bool: ...

class GraphCursorView(Generic[R]):
    def __init__(
        self, cursor: native.GraphCursor, decode: Callable[..., R]
    ) -> None: ...
    def before(self, value: Any) -> GraphCursorView[R]: ...
    def after(self, value: Any) -> GraphCursorView[R]: ...
    def before_with(self, *values: Any) -> GraphCursorView[R]: ...
    def after_with(self, *values: Any) -> GraphCursorView[R]: ...
    def first(self, count: int) -> GraphCursorView[R]: ...
    def last(self, count: int) -> GraphCursorView[R]: ...
    def asc(self) -> GraphCursorView[R]: ...
    def desc(self) -> GraphCursorView[R]: ...
    async def all(self, connection: Connection) -> list[R]: ...
    def __bool__(self) -> bool: ...
