[package]
name = "pgorm-python-codegen-entities"
version = "0.2.0"
edition = "2024"
publish = false
license = "MIT OR Apache-2.0"

[workspace]

[dependencies]
pgorm = { path = "../../.." }
serde = { version = "1.0.229", features = ["derive"] }
async-trait = "0.1.92"
tokio = { version = "1.53.2", features = ["time"] }

[lints.rust]
unsafe_code = "forbid"
