"""Create a native module project without executing a build or database query."""

import json
from functools import partial
from pathlib import Path
from os import PathLike
import shutil
import tomllib

from .config import CodegenError, identifier, rust_string, validate


# [spec:pgorm:req:python.codegen]
def scaffold(
    config: object,
    destination: str | PathLike[str],
    *,
    pgorm_source: str | PathLike[str],
    base: str | PathLike[str] = ".",
) -> Path:
    from .. import capabilities

    description = validate(config, base)
    source = Path(pgorm_source).resolve()
    try:
        version = tomllib.loads((source / "pgorm-python/Cargo.toml").read_text())[
            "package"
        ]["version"]
        pgorm_version = tomllib.loads((source / "Cargo.toml").read_text())["package"][
            "version"
        ]
    except (OSError, KeyError, tomllib.TOMLDecodeError) as error:
        raise CodegenError(
            "pgorm_source must contain compatible pgorm and pgorm-python crates"
        ) from error
    installed = capabilities()
    if (
        version != installed["package_version"]
        or pgorm_version != installed["pgorm_version"]
    ):
        raise CodegenError("source versions differ from this installed code generator")
    facade = Path(__file__).resolve().parents[1]
    module = description["module"]
    omitted = set()
    marker = facade / "_application_module.json"
    if marker.exists():
        try:
            previous = identifier(
                json.loads(marker.read_text())["module"], "generated application module"
            )
        except (OSError, KeyError, json.JSONDecodeError) as error:
            raise CodegenError(
                "installed application module marker is invalid"
            ) from error
        omitted.update({previous + ".py", previous + ".pyi", marker.name})
    if any(
        (facade / (module + suffix)).exists() and module + suffix not in omitted
        for suffix in ("", ".py", ".pyi")
    ):
        raise CodegenError("application module would overwrite the shared pgorm API")
    destination = Path(destination).resolve()
    if destination.exists():
        raise CodegenError(
            "scaffold destination already exists; choose a new directory"
        )
    destination.mkdir(parents=True)
    (destination / "src").mkdir()

    def ignore(directory: str, names: list[str]) -> set[str]:
        skipped = set(
            shutil.ignore_patterns("__pycache__", "*.pyc", "*.so", "*.pyd", "*.dylib")(
                directory, names
            )
        )
        return skipped | (
            omitted.intersection(names) if Path(directory) == facade else set()
        )

    shutil.copytree(facade, destination / "python/pgorm", ignore=ignore)
    # Fixed TOML keys keep application paths and names in string values.
    quote = partial(json.dumps, ensure_ascii=False)
    cargo = f"""[package]
name = "pgorm-application-binding"
version = {quote(version)}
edition = "2024"
publish = false
license = "MIT OR Apache-2.0"

[workspace]

[lib]
name = "_native"
crate-type = ["cdylib", "rlib"]

[features]
extension-module = ["pyo3/extension-module"]

[dependencies]
pgorm-python = {{ path = {quote(str(source / "pgorm-python"))}, version = {quote("=" + version)}, default-features = false }}
pgorm = {{ path = {quote(str(source))}, version = {quote("=" + pgorm_version)} }}
pyo3 = "=0.29.2"
app_entities = {{ package = {quote(description["entity_package"])}, path = {quote(description["entity_crate"])} }}

[lints.rust]
unsafe_code = "forbid"
"""
    (destination / "Cargo.toml").write_text(cargo)
    pyproject = f"""[build-system]
requires = ["maturin==1.15.0"]
build-backend = "maturin"

[project]
name = "pgorm"
version = {quote(version)}
requires-python = ">=3.14,<3.15"
description = "Application registrations over the native pgorm builders"
license = "MIT OR Apache-2.0"

[tool.maturin]
bindings = "pyo3"
python-source = "python"
module-name = "pgorm._native"
features = ["extension-module"]
"""
    (destination / "pyproject.toml").write_text(pyproject)
    for license in ("LICENSE-APACHE", "LICENSE-MIT"):
        shutil.copyfile(source / license, destination / license)
    lines = [
        "// Generated by pgorm.codegen; registration types are checked by Rust.",
        "use pyo3::prelude::*;",
        "",
        "#[pymodule(gil_used = true)]",
        "fn _native(module: &Bound<'_, PyModule>) -> PyResult<()> {",
        "    let mut registry = pgorm_python::entities::Registry::default();",
    ]
    for entry in description["entities"]:
        lines.append(
            f"    registry.entity::<app_entities::{entry['rust']}>({rust_string(entry['name'])})?;"
        )
    for entry in description["graphs"]:
        lines.append(
            f"    registry.graph({rust_string(entry['name'])}, app_entities::{entry['rust']})?;"
        )
    lines.extend(["    pgorm_python::install(module, registry)", "}", ""])
    (destination / "src/lib.rs").write_text("\n".join(lines))
    description["compatibility"] = {
        "package_version": version,
        "pgorm_version": pgorm_version,
        "registry_abi": installed["binding"]["registry_abi"],
    }
    (destination / "application.json").write_text(
        json.dumps(description, ensure_ascii=False, indent=2) + "\n"
    )
    return destination
