//! The generation pipeline itself: what `EntityTransformer::transform` +
//! `EntityWriter::generate` return, which files come out, and how
//! `EntityWriterContext` normalizes its options.

mod common;

use common::*;
use pgorm_codegen::{DateTimeCrate, EntityTransformer, Error, WithSerde};
use pgorm_query::{Alias, ColumnDef, ColumnType, Table};
use std::path::Path;

const HEADER: &str = concat!(
    "//! `pgorm` Entity, @generated by pgorm-codegen ",
    env!("CARGO_PKG_VERSION")
);

fn vendor_schema() -> Vec<pgorm_query::TableCreateStatement> {
    vec![
        Table::create()
            .table(Alias::new("vendor"))
            .col(serial_pk("id"))
            .col(
                ColumnDef::new(Alias::new("name"))
                    .string()
                    .not_null()
                    .to_owned(),
            )
            .index(&mut unique_index("vendor", "name"))
            .to_owned(),
    ]
}

fn enum_schema() -> Vec<pgorm_query::TableCreateStatement> {
    vec![table_with(
        "task",
        vec![
            serial_pk("id"),
            enum_col("state", "task_state", &["open", "done"]),
        ],
    )]
}

// [spec:pgorm:def:codegen.entity/test]    transform -> generate hands back named
// files in memory; the writer itself never touches the filesystem
#[test]
fn pipeline_returns_output_files_without_writing_to_disk() {
    let generated = generate(cake_schema(), Opts::default());

    assert_eq!(
        generated.names(),
        [
            "cake.rs",
            "cake_filling.rs",
            "filling.rs",
            "fruit.rs",
            "mod.rs",
            "prelude.rs",
        ]
    );
    for (name, content) in &generated.files {
        assert!(!content.is_empty(), "{name} should carry content");
        assert!(
            !Path::new(name).exists(),
            "{name} must not have been written to disk by the writer"
        );
    }
}

// [spec:pgorm:def:codegen.entity/test]    the Entity model's table name, column
// facts (type, auto_increment, not_null, unique), relations, conjunct relations
// and primary keys all reach the generated output
#[test]
fn entity_model_carries_column_relation_and_pk_facts() {
    let generated = generate(cake_schema(), Opts::default());
    let cake = generated.file("cake.rs");

    assert_contains(cake, r#"#[pgorm(table_name = "cake")]"#);
    // auto_increment + not_null primary key, and a nullable text column
    assert_contains(cake, "#[pgorm(primary_key)] pub id: i32,");
    assert_contains(
        cake,
        r#"#[pgorm(column_type = "Text", nullable)] pub name: Option<String>,"#,
    );
    // relations
    assert_contains(
        cake,
        r#"#[pgorm(has_many = "super::fruit::Entity")] Fruit,"#,
    );
    // conjunct relations, reached through the junction table
    assert_contains(cake, "impl Related<super::filling::Entity> for Entity");

    // `unique` is the remaining column fact
    let vendor = generate(vendor_schema(), Opts::default());
    assert_contains(
        vendor.file("vendor.rs"),
        "#[pgorm(unique)] pub name: String,",
    );
}

// [spec:pgorm:def:codegen.entity/test]    errors are the two-variant `Error` enum
#[test]
fn errors_are_the_two_variant_error_enum() {
    let nameless = Table::create().col(serial_pk("id")).to_owned();
    match EntityTransformer::transform(vec![nameless]) {
        Err(Error::TransformError(msg)) => assert_eq!(msg, "Table name should not be empty"),
        other => panic!("expected Error::TransformError, got {other:?}"),
    }

    let from_io: Error = std::io::Error::other("boom").into();
    assert!(matches!(from_io, Error::StdIoError(_)));
}

// [spec:pgorm:def:codegen.entity/test]    every `EntityWriterContext` option
// selects something in the generated output
#[test]
fn every_context_option_selects_generated_output() {
    let schema = || {
        vec![table_with(
            "task",
            vec![
                serial_pk("id"),
                enum_col("state", "task_state", &["open", "done"]),
                ColumnDef::new_with_type(Alias::new("_secret"), ColumnType::Integer)
                    .not_null()
                    .to_owned(),
                ColumnDef::new_with_type(Alias::new("due"), ColumnType::Timestamp).to_owned(),
            ],
        )]
    };

    // expanded_format
    assert_contains(
        generate(schema(), Opts::expanded()).file("task.rs"),
        "pub struct Entity;",
    );
    assert_not_contains(
        generate(schema(), Opts::default()).file("task.rs"),
        "pub struct Entity;",
    );

    // with_serde + serde_skip_hidden_column + serde_skip_deserializing_primary_key
    let serde = generate(
        schema(),
        Opts {
            with_serde: WithSerde::Both,
            serde_skip_hidden_column: true,
            serde_skip_deserializing_primary_key: true,
            ..Default::default()
        },
    );
    assert_contains(
        serde.file("task.rs"),
        "use serde::{Deserialize, Serialize};",
    );
    assert_contains(serde.file("task.rs"), "#[serde(skip)] pub secret: i32,");
    assert_contains(
        serde.file("task.rs"),
        "#[serde(skip_deserializing)] pub id: i32,",
    );

    // with_copy_enums + enum_extra_derives + enum_extra_attributes
    let enums = generate(
        schema(),
        Opts {
            with_copy_enums: true,
            enum_extra_derives: vec!["Hash".to_owned()],
            enum_extra_attributes: vec!["non_exhaustive".to_owned()],
            ..Default::default()
        },
    );
    assert_contains(
        enums.file("pgorm_active_enums.rs"),
        "#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Copy, Hash)]",
    );
    assert_contains(enums.file("pgorm_active_enums.rs"), "#[non_exhaustive]");

    // date_time_crate
    assert_contains(
        generate(
            schema(),
            Opts {
                date_time_crate: DateTimeCrate::Time,
                ..Default::default()
            },
        )
        .file("task.rs"),
        "pub due: Option<TimeDateTime>,",
    );

    // schema_name
    assert_contains(
        generate(
            schema(),
            Opts {
                schema_name: Some("public".to_owned()),
                ..Default::default()
            },
        )
        .file("task.rs"),
        r#"#[pgorm(schema_name = "public", table_name = "task")]"#,
    );

    // lib
    assert!(
        generate(
            schema(),
            Opts {
                lib: true,
                ..Default::default()
            },
        )
        .has("lib.rs")
    );

    // model_extra_derives + model_extra_attributes
    let model_extras = generate(
        schema(),
        Opts {
            model_extra_derives: vec!["Default".to_owned()],
            model_extra_attributes: vec![r#"serde(rename_all = "camelCase")"#.to_owned()],
            ..Default::default()
        },
    );
    assert_contains(
        model_extras.file("task.rs"),
        "#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Default)]",
    );
    assert_contains(
        model_extras.file("task.rs"),
        r#"#[serde(rename_all = "camelCase")]"#,
    );

    // seaography
    assert_contains(
        generate(
            schema(),
            Opts {
                seaography: true,
                ..Default::default()
            },
        )
        .file("task.rs"),
        "pub enum RelatedEntity",
    );
}

// [spec:pgorm:req:codegen.entity.files/test]    one entity file per entity, plus
// the index file and prelude
#[test]
fn generate_emits_entity_files_index_and_prelude() {
    let generated = generate(cake_schema(), Opts::default());

    assert_eq!(
        generated.names(),
        [
            "cake.rs",
            "cake_filling.rs",
            "filling.rs",
            "fruit.rs",
            "mod.rs",
            "prelude.rs",
        ]
    );
}

// [spec:pgorm:req:codegen.entity.files/test]    `pgorm_active_enums.rs` iff at
// least one enum was discovered
#[test]
fn active_enums_file_emitted_only_when_enums_exist() {
    assert!(!generate(cake_schema(), Opts::default()).has("pgorm_active_enums.rs"));
    assert!(generate(enum_schema(), Opts::default()).has("pgorm_active_enums.rs"));
}

// [spec:pgorm:req:codegen.entity.files/test]    every generated file starts with
// the generated-by header
#[test]
fn every_generated_file_starts_with_the_header_line() {
    let generated = generate(enum_schema(), Opts::default());
    assert!(generated.has("pgorm_active_enums.rs"));

    for (name, content) in &generated.files {
        assert_eq!(
            content.lines().next(),
            Some(HEADER),
            "{name} should start with the generated-file header"
        );
    }
}

// [spec:pgorm:req:codegen.entity.files/test]    index file is `lib.rs` when `lib`
// is set and `mod.rs` otherwise
#[test]
fn index_file_name_follows_the_lib_flag() {
    let as_mod = generate(cake_schema(), Opts::default());
    assert!(as_mod.has("mod.rs") && !as_mod.has("lib.rs"));

    let as_lib = generate(
        cake_schema(),
        Opts {
            lib: true,
            ..Default::default()
        },
    );
    assert!(as_lib.has("lib.rs") && !as_lib.has("mod.rs"));
}

// [spec:pgorm:req:codegen.entity.files/test]    index file order: prelude, then
// entity modules alphabetically, then the active-enums module last
#[test]
fn index_file_lists_prelude_entities_then_active_enums() {
    let mut schema = cake_schema();
    schema.push(table_with(
        "task",
        vec![
            serial_pk("id"),
            enum_col("state", "task_state", &["open", "done"]),
        ],
    ));

    let generated = generate(schema, Opts::default());
    let lines: Vec<&str> = generated
        .file("mod.rs")
        .lines()
        .filter(|l| !l.is_empty())
        .collect();

    assert_eq!(
        lines,
        [
            HEADER,
            "pub mod prelude ;",
            "pub mod cake ;",
            "pub mod cake_filling ;",
            "pub mod filling ;",
            "pub mod fruit ;",
            "pub mod task ;",
            "pub mod pgorm_active_enums ;",
        ]
    );
}

// [spec:pgorm:req:codegen.entity.files/test]    `prelude.rs` re-exports one
// `Entity` per entity
#[test]
fn prelude_reexports_every_entity() {
    let generated = generate(cake_schema(), Opts::default());
    let lines: Vec<&str> = generated
        .file("prelude.rs")
        .lines()
        .filter(|l| !l.is_empty())
        .collect();

    assert_eq!(
        lines,
        [
            HEADER,
            "pub use super :: cake :: Entity as Cake ;",
            "pub use super :: cake_filling :: Entity as CakeFilling ;",
            "pub use super :: filling :: Entity as Filling ;",
            "pub use super :: fruit :: Entity as Fruit ;",
        ]
    );
}

// [spec:pgorm:req:codegen.entity.files/test]    entity-file code blocks are
// joined with blank lines and left unformatted
#[test]
fn entity_file_blocks_are_joined_with_blank_lines() {
    let generated = generate(cake_schema(), Opts::default());
    let fruit = generated.file("fruit.rs");

    let blocks = blocks(fruit);
    assert_eq!(
        blocks.len(),
        5,
        "one block per compact section: {blocks:#?}"
    );
    assert!(blocks[0].starts_with("use pgorm :: entity :: prelude"));
    assert!(blocks[1].starts_with("# [derive (Clone , Debug , PartialEq , DeriveEntityModel"));
    assert!(blocks[2].starts_with("# [derive (Copy , Clone , Debug , EnumIter , DeriveRelation)]"));
    assert!(blocks[3].starts_with("impl Related < super :: cake :: Entity >"));
    assert_eq!(blocks[4], "impl ActiveModelBehavior for ActiveModel { }");

    // unformatted TokenStream text: no rustfmt-style newlines inside a block
    assert!(
        !blocks[1].contains('\n'),
        "blocks are single unformatted lines"
    );
}

// [spec:pgorm:sem:codegen.entity.context/test]    `bonus_derive` folds extra
// derives into one leading-comma fragment appended to the derive list
#[test]
fn context_folds_extra_derives_into_comma_fragment() {
    let generated = generate(
        enum_schema(),
        Opts {
            model_extra_derives: vec!["Default".to_owned(), "Hash".to_owned()],
            enum_extra_derives: vec!["Hash".to_owned(), "PartialOrd".to_owned()],
            ..Default::default()
        },
    );

    assert_contains(
        generated.file("task.rs"),
        "#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Default, Hash)]",
    );
    assert_contains(
        generated.file("pgorm_active_enums.rs"),
        "#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Hash, PartialOrd)]",
    );
}

// [spec:pgorm:sem:codegen.entity.context/test]    `bonus_attributes` wraps each
// extra attribute in its own `#[...]` line
#[test]
fn context_wraps_each_extra_attribute_in_own_line() {
    let generated = generate(
        enum_schema(),
        Opts {
            model_extra_attributes: vec![
                r#"serde(rename_all = "camelCase")"#.to_owned(),
                "allow(dead_code)".to_owned(),
            ],
            enum_extra_attributes: vec!["non_exhaustive".to_owned()],
            ..Default::default()
        },
    );

    assert_contains(
        generated.file("task.rs"),
        r#"#[serde(rename_all = "camelCase")] #[allow(dead_code)] pub struct Model"#,
    );
    assert_contains(
        generated.file("pgorm_active_enums.rs"),
        "#[non_exhaustive] pub enum TaskState",
    );
}

// [spec:pgorm:sem:codegen.entity.context/test]    an unparsable extra derive
// panics at context construction, before any file is generated
#[test]
#[should_panic]
fn context_panics_on_unparsable_extra_derive() {
    let _ctx = Opts {
        model_extra_derives: vec!["(".to_owned()],
        ..Default::default()
    }
    .build();
}

// [spec:pgorm:sem:codegen.entity.context/test]    the same holds for an
// unparsable extra attribute
#[test]
#[should_panic]
fn context_panics_on_unparsable_extra_attribute() {
    let _ctx = Opts {
        enum_extra_attributes: vec!["(".to_owned()],
        ..Default::default()
    }
    .build();
}

// [spec:pgorm:sem:codegen.entity.context/test]    `date_time_crate` is threaded
// into Model field types and the expanded `PrimaryKeyTrait::ValueType`
#[test]
fn context_threads_date_time_crate_into_model_pk() {
    let schema = || {
        vec![table_with(
            "event",
            vec![
                ColumnDef::new_with_type(Alias::new("at"), ColumnType::Date)
                    .not_null()
                    .primary_key()
                    .to_owned(),
                ColumnDef::new_with_type(Alias::new("seen"), ColumnType::Timestamp)
                    .not_null()
                    .to_owned(),
            ],
        )]
    };

    let chrono = generate(schema(), Opts::expanded());
    assert_contains(chrono.file("event.rs"), "pub at: Date,");
    assert_contains(chrono.file("event.rs"), "pub seen: DateTimeUtc,");
    assert_contains(chrono.file("event.rs"), "type ValueType = Date;");

    let time = generate(
        schema(),
        Opts {
            expanded_format: true,
            date_time_crate: DateTimeCrate::Time,
            ..Default::default()
        },
    );
    assert_contains(time.file("event.rs"), "pub at: TimeDate,");
    assert_contains(time.file("event.rs"), "pub seen: TimeDateTime,");
    assert_contains(time.file("event.rs"), "type ValueType = TimeDate;");
}
