[package]
name = "pgorm-macros"
version = "0.2.0"
authors = [ "Billy Chan <ccw.billy.123@gmail.com>" ]
edition = "2024"
description = "Derive macros for pgorm"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/pgorm-rs/pgorm"
documentation = "https://docs.rs/pgorm-macros"
repository = "https://github.com/pgorm-rs/pgorm"
categories = [ "database" ]
keywords = ["async", "orm", "postgres"]
rust-version = "1.88"

[lib]
name = "pgorm_macros"
path = "src/lib.rs"
proc-macro = true

[dependencies]
syn = { version = "3", default-features = false, features = ["parsing", "proc-macro", "derive", "printing", "clone-impls", "extra-traits", "full"] }
quote = { version = "1.0.47", default-features = false }
heck = { version = "0.5", default-features = false }
proc-macro2 = { version = "1.0.107", default-features = false }
unicode-ident = { version = "1.0.24" }

[dev-dependencies]
pgorm = { path = "../", features = ["macros", "tests-cfg"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = { version = "1.0.151" }
trybuild = "1.0.120"

[features]
default = ["derive"]
postgres-array = []
derive = []
strum = []
