"""Compose native pgorm builders and execute them directly against PostgreSQL."""

from ._native import (
    PgOrmError,
    CancelledError,
    ConnectionError,
    ConstructionError,
    DatabaseError,
    DecodeError,
    InternalError,
    LifecycleError,
    TimeoutError,
    UnsupportedCapabilityError,
    TypeName,
    Value,
    Identifier,
    Direction,
    Nulls,
    Expr,
    Condition,
    LikePattern,
    AliasedExpr,
    OrderBy,
    Compiled,
    col,
    bind,
    literal,
    call,
    tuple_expr,
    Table,
    Select,
    Join,
    Insert,
    Update,
    Delete,
    Conflict,
    ConflictTarget,
    ConflictUpdate,
    RawSQL,
    __pgorm_version__,
    __version__,
    capabilities,
    require_capability,
)
from .runtime import Connection, Pool, PoolStatus, connect

select = Select
insert = Insert
update = Update
delete = Delete

__all__ = [
    "PgOrmError",
    "CancelledError",
    "ConnectionError",
    "ConstructionError",
    "DatabaseError",
    "DecodeError",
    "InternalError",
    "LifecycleError",
    "TimeoutError",
    "Connection",
    "Pool",
    "PoolStatus",
    "connect",
    "UnsupportedCapabilityError",
    "TypeName",
    "Value",
    "Identifier",
    "Direction",
    "Nulls",
    "Expr",
    "Condition",
    "LikePattern",
    "AliasedExpr",
    "OrderBy",
    "Compiled",
    "col",
    "bind",
    "literal",
    "call",
    "tuple_expr",
    "Table",
    "Select",
    "Join",
    "Insert",
    "Update",
    "Delete",
    "Conflict",
    "ConflictTarget",
    "ConflictUpdate",
    "RawSQL",
    "select",
    "insert",
    "update",
    "delete",
    "__pgorm_version__",
    "__version__",
    "capabilities",
    "require_capability",
]
