from typing import Never
from ._expressions import Expr
from ._query_types import Compiled

class Condition:
    def __init__(self, _native_only: Never, /) -> None: ...
    @staticmethod
    def all(*conditions: Expr | Condition) -> Condition: ...
    @staticmethod
    def any(*conditions: Expr | Condition) -> Condition: ...
    def add(self, /, other: Expr | Condition) -> Condition: ...
    def __invert__(self, /) -> Condition: ...
    def inspect(self, /) -> Compiled: ...
