from typing import Any
from collections.abc import Awaitable
from ._native import Identifier, Expr, Condition, Compiled, OrderBy
from ._entity_models import ActiveModel, EntityModel
from .runtime import Connection

class Entity:
    @property
    def name(self) -> str: ...
    def describe(self) -> dict[str, Any]: ...
    def col(self, name: str | Identifier) -> EntityColumn: ...
    def find(self) -> EntityQuery: ...
    def active(self) -> ActiveModel: ...

class EntityColumn:
    @property
    def name(self) -> str: ...
    @property
    def entity_name(self) -> str: ...
    def describe(self) -> dict[str, Any]: ...
    def expr(self) -> Expr: ...
    def eq(self, value: Any) -> Expr: ...
    def ne(self, value: Any) -> Expr: ...
    def gt(self, value: Any) -> Expr: ...
    def gte(self, value: Any) -> Expr: ...
    def lt(self, value: Any) -> Expr: ...
    def lte(self, value: Any) -> Expr: ...
    def __eq__(self, value: Any) -> Expr: ...  # type: ignore[override]
    def __ne__(self, value: Any) -> Expr: ...  # type: ignore[override]
    def __gt__(self, value: Any) -> Expr: ...
    def __ge__(self, value: Any) -> Expr: ...
    def __lt__(self, value: Any) -> Expr: ...
    def __le__(self, value: Any) -> Expr: ...
    def __bool__(self) -> bool: ...

class EntityQuery:
    @property
    def entity_name(self) -> str: ...
    def filter(self, predicate: Expr | Condition) -> EntityQuery: ...
    def order_by(self, *ordering: OrderBy) -> EntityQuery: ...
    def limit(self, value: int | None = ...) -> EntityQuery: ...
    def offset(self, value: int | None = ...) -> EntityQuery: ...
    def inspect(self, *, terminal: str = ...) -> Compiled: ...
    def all(self, connection: Connection) -> Awaitable[list[EntityModel]]: ...
    def one(self, connection: Connection) -> Awaitable[EntityModel]: ...
    def one_opt(self, connection: Connection) -> Awaitable[EntityModel | None]: ...
    def __bool__(self) -> bool: ...

def entity(name: str) -> Entity: ...
