from .transactions import Transaction
from typing import Any, Never
from collections.abc import Awaitable, Iterator
from ._native import Value, Identifier
from ._entities import EntityColumn
from .runtime import Connection

class ActiveState:
    def __init__(self, _native_only: Never, /) -> None: ...
    NotSet: ActiveState
    Set: ActiveState
    Unchanged: ActiveState

class ActiveValue:
    def __init__(self, _native_only: Never, /) -> None: ...
    @property
    def state(self) -> ActiveState: ...
    @property
    def value(self) -> Value | None: ...

class ActiveModel:
    def __init__(self, _native_only: Never, /) -> None: ...
    @property
    def entity_name(self) -> str: ...
    def get(self, /, column: str | Identifier | EntityColumn) -> ActiveValue: ...
    def set(self, /, column: str | Identifier | EntityColumn, value: Any) -> ActiveModel: ...
    def not_set(self, /, column: str | Identifier | EntityColumn) -> ActiveModel: ...
    def reset(self, /, column: str | Identifier | EntityColumn) -> ActiveModel: ...
    def insert(self, /, connection: Connection | Transaction) -> Awaitable[EntityModel]: ...
    def update(self, /, connection: Connection | Transaction) -> Awaitable[EntityModel]: ...
    def delete(self, /, connection: Connection | Transaction) -> Awaitable[int]: ...

class EntityModel:
    def __init__(self, _native_only: Never, /) -> None: ...
    @property
    def entity_name(self) -> str: ...
    def __getitem__(self, key: str, /) -> Any: ...
    def __len__(self, /) -> int: ...
    def __iter__(self, /) -> Iterator[str]: ...
    def keys(self, /) -> tuple[str, ...]: ...
    def values(self, /) -> tuple[Any, ...]: ...
    def items(self, /) -> tuple[tuple[str, Any], ...]: ...
    def tagged(self, /, name: str) -> Value: ...
    def with_value(self, /, column: str | Identifier | EntityColumn, value: Any) -> EntityModel: ...
    def into_active(self, /) -> ActiveModel: ...
