from typing import Any, Never
from ._native import TypeName
from ._query_types import AliasedExpr, Compiled, Identifier, LikePattern, Nulls, OrderBy

class Expr:
    def __init__(self, _native_only: Never, /) -> None: ...
    def eq(self, /, other: Any) -> Expr: ...
    def ne(self, /, other: Any) -> Expr: ...
    def gt(self, /, other: Any) -> Expr: ...
    def gte(self, /, other: Any) -> Expr: ...
    def lt(self, /, other: Any) -> Expr: ...
    def lte(self, /, other: Any) -> Expr: ...
    def __eq__(self, value: object, /) -> Expr: ...  # type: ignore[override]
    def __ne__(self, value: object, /) -> Expr: ...  # type: ignore[override]
    def __lt__(self, value: Any, /) -> Expr: ...
    def __le__(self, value: Any, /) -> Expr: ...
    def __gt__(self, value: Any, /) -> Expr: ...
    def __ge__(self, value: Any, /) -> Expr: ...
    def __add__(self, value: Any, /) -> Expr: ...
    def __sub__(self, value: Any, /) -> Expr: ...
    def __mul__(self, value: Any, /) -> Expr: ...
    def __truediv__(self, value: Any, /) -> Expr: ...
    def __mod__(self, value: Any, /) -> Expr: ...
    def __and__(self, value: Expr, /) -> Expr: ...
    def __or__(self, value: Expr, /) -> Expr: ...
    def __invert__(self, /) -> Expr: ...
    def is_null(self, /) -> Expr: ...
    def is_not_null(self, /) -> Expr: ...
    def is_in(self, /, values: list[Any] | tuple[Any, ...]) -> Expr: ...
    def is_not_in(self, /, values: list[Any] | tuple[Any, ...]) -> Expr: ...
    def between(self, /, lower: Any, upper: Any) -> Expr: ...
    def not_between(self, /, lower: Any, upper: Any) -> Expr: ...
    def cast(self, /, type_name: TypeName, *, array: bool = ...) -> Expr: ...
    def as_(self, /, alias: str | Identifier) -> AliasedExpr: ...
    def asc(self, /, *, nulls: Nulls | None = ...) -> OrderBy: ...
    def desc(self, /, *, nulls: Nulls | None = ...) -> OrderBy: ...
    def starts_with(self, /, text: Any) -> Expr: ...
    def contains_text(self, /, text: Any) -> Expr: ...
    def ends_with(self, /, text: Any) -> Expr: ...
    def like(self, /, pattern: LikePattern) -> Expr: ...
    def not_like(self, /, pattern: LikePattern) -> Expr: ...
    def ilike(self, /, pattern: LikePattern) -> Expr: ...
    def not_ilike(self, /, pattern: LikePattern) -> Expr: ...
    def inspect(self, /) -> Compiled: ...

class Condition:
    def __init__(self, _native_only: Never, /) -> None: ...
    @staticmethod
    def all(*conditions: Expr | Condition) -> Condition: ...
    @staticmethod
    def any(*conditions: Expr | Condition) -> Condition: ...
    def add(self, /, other: Expr | Condition) -> Condition: ...
    def __invert__(self, /) -> Condition: ...
    def inspect(self, /) -> Compiled: ...

def col(name: str | Identifier, *, table: str | Identifier | None = ...,
        schema: str | Identifier | None = ...) -> Expr: ...
def bind(value: Any) -> Expr: ...
def literal(value: Any) -> Expr: ...
def call(name: str, *arguments: Any) -> Expr: ...
def tuple_expr(*expressions: Any) -> Expr: ...
