from .transactions import Transaction
from typing import Any, TypeAlias, Never
from collections.abc import Awaitable, Sequence
from ._native import Compiled, Condition, Expr, OrderBy
from ._entity_models import EntityModel
from .runtime import Connection

GraphRow: TypeAlias = EntityModel | tuple[EntityModel | None, ...]

class Graph:
    def __init__(self, _native_only: Never, /) -> None: ...
    @property
    def name(self) -> str: ...
    def describe(self, /) -> dict[str, Any]: ...
    def find(self, /, *, aliases: Sequence[str] | None = ...) -> GraphQuery: ...

class GraphQuery:
    def __init__(self, _native_only: Never, /) -> None: ...
    @property
    def graph_name(self) -> str: ...
    def col(self, /, source: int, column: str) -> Expr: ...
    def filter(self, /, predicate: Expr | Condition) -> GraphQuery: ...
    def order_by(self, /, *ordering: OrderBy) -> GraphQuery: ...
    def inspect(self, /, *, terminal: str = ...) -> Compiled: ...
    def cursor(self, /, column: str) -> GraphCursor: ...
    def all(self, /, connection: Connection | Transaction) -> Awaitable[list[GraphRow]]: ...
    def one_opt(self, /, connection: Connection | Transaction) -> Awaitable[GraphRow | None]: ...
    def __bool__(self, /) -> bool: ...

class GraphCursor:
    def __init__(self, _native_only: Never, /) -> None: ...
    def before(self, /, value: Any) -> GraphCursor: ...
    def after(self, /, value: Any) -> GraphCursor: ...
    def before_with(self, /, *values: Any) -> GraphCursor: ...
    def after_with(self, /, *values: Any) -> GraphCursor: ...
    def first(self, /, count: int) -> GraphCursor: ...
    def last(self, /, count: int) -> GraphCursor: ...
    def asc(self, /) -> GraphCursor: ...
    def desc(self, /) -> GraphCursor: ...
    def all(self, /, connection: Connection | Transaction) -> Awaitable[list[GraphRow]]: ...
    def __bool__(self, /) -> bool: ...

def graph(name: str) -> Graph: ...
