from typing import Any, ClassVar, Never
from ._expressions import Expr, Condition
from ._query_types import AliasedExpr, Compiled, Identifier
from ._statements import Select, Table

class MatchedAction:
    def __init__(self, _native_only: Never, /) -> None: ...
    Delete: ClassVar[MatchedAction]
    DoNothing: ClassVar[MatchedAction]

class NotMatchedAction:
    def __init__(self, _native_only: Never, /) -> None: ...
    InsertDefaultValues: ClassVar[NotMatchedAction]
    DoNothing: ClassVar[NotMatchedAction]

class Overriding:
    def __init__(self, _native_only: Never, /) -> None: ...
    SystemValue: ClassVar[Overriding]
    UserValue: ClassVar[Overriding]

class MergeUpdate:
    def __init__(self, column: str | Identifier, value: Any) -> None: ...
    def and_value(self, /, column: str | Identifier, value: Any) -> MergeUpdate: ...

class MergeInsert:
    def __init__(self, column: str | Identifier, value: Any) -> None: ...
    def and_value(self, /, column: str | Identifier, value: Any) -> MergeInsert: ...
    def overriding(self, /, overriding: Overriding) -> MergeInsert: ...

class PendingMerge:
    def __init__(self, _native_only: Never, /) -> None: ...
    def when_matched(self, /, action: MergeUpdate | MatchedAction, *,
                     condition: Expr | Condition | None = ...) -> Merge: ...
    def when_not_matched(self, /, action: MergeInsert | NotMatchedAction, *,
                         condition: Expr | Condition | None = ...) -> Merge: ...
    def when_not_matched_by_source(self, /, action: MergeUpdate | MatchedAction, *,
                                   condition: Expr | Condition | None = ...) -> Merge: ...

class Merge:
    def __init__(self, _native_only: Never, /) -> None: ...
    def when_matched(self, /, action: MergeUpdate | MatchedAction, *,
                     condition: Expr | Condition | None = ...) -> Merge: ...
    def when_not_matched(self, /, action: MergeInsert | NotMatchedAction, *,
                         condition: Expr | Condition | None = ...) -> Merge: ...
    def when_not_matched_by_source(self, /, action: MergeUpdate | MatchedAction, *,
                                   condition: Expr | Condition | None = ...) -> Merge: ...
    def returning(self, /, *items: Expr | AliasedExpr, old_as: str | Identifier | None = ...,
                  new_as: str | Identifier | None = ...) -> Merge: ...
    def returning_action(self, /) -> Merge: ...
    def with_(self, /, clause: With) -> Merge: ...
    def only(self, /) -> Merge: ...
    def inspect(self, /) -> Compiled: ...

class With:
    def __init__(self, name: str | Identifier, query: Select | Merge) -> None: ...
    def cte(self, /, name: str | Identifier, query: Select | Merge) -> With: ...

class ReturningRow:
    def __init__(self, _native_only: Never, /) -> None: ...
    Old: ClassVar[ReturningRow]
    New: ClassVar[ReturningRow]
    def col(self, /, name: str | Identifier) -> Expr: ...
    def star(self, /) -> Expr: ...

def merge(target: Table, source: Table, on: Expr | Condition) -> PendingMerge: ...
