from typing import Any
from collections.abc import Awaitable
from asyncio import CancelledError as CancelledError

__version__: str
__pgorm_version__: str

class PgOrmError(Exception): ...
class UnsupportedCapabilityError(PgOrmError): ...
class ConstructionError(PgOrmError): ...
class ConnectionError(PgOrmError): ...
class DatabaseError(PgOrmError):
    sqlstate: str
    message: str
    severity: str
    detail: str | None
    hint: str | None
    schema: str | None
    table: str | None
    column: str | None
    constraint: str | None
class DecodeError(PgOrmError): ...
class TimeoutError(PgOrmError): ...
class LifecycleError(PgOrmError): ...
class InternalError(PgOrmError): ...

class _Pool:
    def __init__(self, dsn: str, *, tls: str | None = ..., ca_pem: bytes | None = ...,
                 max_size: int = ..., connect_timeout: float = ...,
                 acquire_timeout: float = ..., statement_cache_size: int = ...,
                 recycle: str = ...) -> None: ...
    def acquire(self) -> Awaitable[_Connection]: ...
    def close(self) -> Awaitable[None]: ...
    def closed(self) -> bool: ...
    def status(self) -> tuple[int, int, int, int]: ...

class _Connection:
    def ping(self) -> Awaitable[bool]: ...
    def close(self) -> Awaitable[None]: ...
    def closed(self) -> bool: ...

def capabilities() -> dict[str, Any]: ...
def require_capability(operation: str) -> None: ...
