from typing import Any, Literal, overload
from collections.abc import Awaitable
from asyncio import CancelledError as CancelledError
from ._schema import (
    DataType as DataType, ColumnDef as ColumnDef, DDL as DDL,
    CreateTable as CreateTable, CreateIndex as CreateIndex, EntitySchema as EntitySchema,
    schema_from_entity as schema_from_entity, drop_table as drop_table,
    rename_table as rename_table, rename_column as rename_column, truncate as truncate,
    add_column as add_column, modify_column as modify_column, drop_column as drop_column,
    drop_index as drop_index, create_enum as create_enum, add_enum_value as add_enum_value,
    rename_enum as rename_enum, rename_enum_value as rename_enum_value, drop_enum as drop_enum,
)
from ._pipeline_builder import Pipeline as Pipeline, PipelineSource as PipelineSource, PipelineGrouped as PipelineGrouped
from ._pipeline_expr import PipelineExpr as PipelineExpr, PipelineBinder as PipelineBinder, PipelineOver as PipelineOver
from ._pipeline_sources import SourceSelection as SourceSelection, SelectedSources as SelectedSources
from ._pipeline_functions import (
    pipeline_source as pipeline_source, pipeline_literal as pipeline_literal,
    pipeline_alias as pipeline_alias, pipeline_col as pipeline_col,
    pipeline_role as pipeline_role, pipeline_function as pipeline_function,
    pipeline_case as pipeline_case, pipeline_sources as pipeline_sources,
)

__version__: str
__pgorm_version__: str

class PgOrmError(Exception): ...
class UnsupportedCapabilityError(PgOrmError): ...
class ConstructionError(PgOrmError): ...
class ConnectionError(PgOrmError): ...
class DatabaseError(PgOrmError):
    sqlstate: str
    message: str
    severity: str
    detail: str | None
    hint: str | None
    schema: str | None
    table: str | None
    column: str | None
    constraint: str | None
class DecodeError(PgOrmError): ...
class TimeoutError(PgOrmError): ...
class LifecycleError(PgOrmError): ...
class InternalError(PgOrmError): ...

class _Pool:
    def __init__(self, dsn: str, *, tls: str | None = ..., ca_pem: bytes | None = ...,
                 max_size: int = ..., connect_timeout: float = ...,
                 acquire_timeout: float = ..., statement_cache_size: int = ...,
                 recycle: str = ...) -> None: ...
    def acquire(self) -> Awaitable[_Connection]: ...
    def close(self) -> Awaitable[None]: ...
    def closed(self) -> bool: ...
    def status(self) -> tuple[int, int, int, int]: ...

class _Connection:
    def begin(self, *, mode: str = ..., isolation: str | None = ...) -> Awaitable[_Transaction]: ...
    def ping(self) -> Awaitable[bool]: ...
    def close(self) -> Awaitable[None]: ...
    def closed(self) -> bool: ...
    def execute(self, query: Any) -> Awaitable[int]: ...
    @overload
    def fetch(self, query: Any, mode: Literal["all"]) -> Awaitable[list[Record]]: ...
    @overload
    def fetch(self, query: Any, mode: Literal["one"]) -> Awaitable[Record]: ...
    @overload
    def fetch(self, query: Any, mode: Literal["optional"]) -> Awaitable[Record | None]: ...
    def stream(self, query: Any) -> Awaitable[_Stream]: ...

class _Stream:
    def next(self) -> Awaitable[Record | None]: ...
    def close(self) -> Awaitable[None]: ...
    def closed(self) -> bool: ...

class _Transaction:
    def begin(self) -> Awaitable[_Transaction]: ...
    def finish(self, commit: bool) -> Awaitable[None]: ...
    def wait_closed(self) -> Awaitable[None]: ...
    def closed(self) -> bool: ...
    def owner_matches(self, parent: object) -> bool: ...
    def abort(self) -> Awaitable[None]: ...
    def execute(self, query: Any) -> Awaitable[int]: ...
    @overload
    def fetch(self, query: Any, mode: Literal["all"]) -> Awaitable[list[Record]]: ...
    @overload
    def fetch(self, query: Any, mode: Literal["one"]) -> Awaitable[Record]: ...
    @overload
    def fetch(self, query: Any, mode: Literal["optional"]) -> Awaitable[Record | None]: ...

def capabilities() -> dict[str, Any]: ...
def require_capability(operation: str) -> None: ...

class TypeName:
    def __init__(self, name: str, *, schema: str | None = ...) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def schema(self) -> str | None: ...

class Value:
    def __init__(self, value: Any, kind: str | TypeName | None = ...) -> None: ...
    @staticmethod
    def null(kind: str | TypeName) -> Value: ...
    @staticmethod
    def json(value: Any) -> Value: ...
    @staticmethod
    def array(kind: str | TypeName, values: list[Any] | tuple[Any, ...] | None) -> Value: ...
    @property
    def kind(self) -> str: ...
    @property
    def is_null(self) -> bool: ...
    @property
    def value(self) -> Any: ...
    @property
    def type_name(self) -> TypeName | None: ...
    @property
    def element_type(self) -> str | TypeName | None: ...
    def items(self) -> list[Value] | None: ...
    def snapshot(self) -> dict[str, Any]: ...

from ._query_types import (
    Identifier as Identifier, Direction as Direction, Nulls as Nulls,
    Compiled as Compiled, LikePattern as LikePattern,
    AliasedExpr as AliasedExpr, OrderBy as OrderBy,
)
from ._expressions import (
    Expr as Expr, Condition as Condition, col as col, bind as bind,
    literal as literal, call as call, tuple_expr as tuple_expr,
)
from ._statements import Table as Table, Select as Select, Join as Join
from ._results import Record as Record, Field as Field
from ._entities import Entity as Entity, EntityColumn as EntityColumn, EntityQuery as EntityQuery, entity as entity
from ._graphs import Graph as Graph, GraphQuery as GraphQuery, GraphCursor as GraphCursor, graph as graph
from ._entity_models import EntityModel as EntityModel, ActiveModel as ActiveModel, ActiveValue as ActiveValue, ActiveState as ActiveState
from ._writes import (
    Insert as Insert, Update as Update, Delete as Delete, RawSQL as RawSQL,
    Conflict as Conflict, ConflictTarget as ConflictTarget, ConflictUpdate as ConflictUpdate,
)
