from typing import Any

__version__: str
__pgorm_version__: str

class PgOrmError(Exception): ...
class UnsupportedCapabilityError(PgOrmError): ...

def capabilities() -> dict[str, Any]: ...
def require_capability(operation: str) -> None: ...
