from collections.abc import Awaitable, Callable
from typing import TypeAlias, Literal
from ._native import Table, Entity, Join, Compiled, Record
from .runtime import Connection
from ._pipeline_expr import Operand, Name, PipelineExpr, PipelineBinder, PipelineOver
from ._pipeline_sources import SourceSelection, SelectedSources

SourceInput: TypeAlias = Table | Entity | Pipeline | PipelineSource
BoundScalar: TypeAlias = Callable[[PipelineBinder], Operand]
BoundList: TypeAlias = Callable[
    [PipelineBinder], PipelineExpr | list[Operand] | tuple[Operand, ...]
]

class PipelineSource:
    def named(self, name: Name) -> PipelineSource: ...

class Pipeline:
    def __init__(self, source: SourceInput) -> None: ...
    def filter(self, condition: Operand) -> Pipeline: ...
    def filter_with(self, function: BoundScalar) -> Pipeline: ...
    def derive(self, *columns: Operand) -> Pipeline: ...
    def derive_with(self, function: BoundList) -> Pipeline: ...
    def select(self, *columns: Operand) -> Pipeline: ...
    def select_with(self, function: BoundList) -> Pipeline: ...
    def group(self, *keys: Operand) -> PipelineGrouped: ...
    def group_with(self, function: BoundList) -> PipelineGrouped: ...
    def window(self, *columns: Operand, over: PipelineOver) -> Pipeline: ...
    def window_with(self, over: PipelineOver, function: BoundList) -> Pipeline: ...
    def sort(self, *keys: Operand) -> Pipeline: ...
    def sort_with(self, function: BoundList) -> Pipeline: ...
    def take(self, rows: int) -> Pipeline: ...
    def take_range(self, start: int, end: int) -> Pipeline: ...
    def join(
        self, source: SourceInput, on: Operand, *, kind: Join = ...
    ) -> Pipeline: ...
    def join_with(
        self, source: SourceInput, function: BoundScalar, *, kind: Join = ...
    ) -> Pipeline: ...
    def append(self, source: SourceInput) -> Pipeline: ...
    def intersect(self, source: SourceInput) -> Pipeline: ...
    def remove(self, source: SourceInput) -> Pipeline: ...
    def distinct(self) -> Pipeline: ...
    def inspect(
        self, *, terminal: Literal["all", "one", "one_opt"] = ...
    ) -> Compiled: ...
    def all(self, connection: Connection) -> Awaitable[list[Record]]: ...
    def one(self, connection: Connection) -> Awaitable[Record]: ...
    def one_opt(self, connection: Connection) -> Awaitable[Record | None]: ...
    def select_sources(
        self,
        selection: SourceSelection,
        *,
        qualifiers: list[str] | tuple[str, ...] | None = ...,
    ) -> SelectedSources: ...

class PipelineGrouped:
    def aggregate(self, *columns: Operand) -> Pipeline: ...
    def aggregate_with(self, function: BoundList) -> Pipeline: ...
