from ._pipeline_builder import PipelineSource, SourceInput
from ._pipeline_expr import PipelineExpr, Operand, Name
from ._pipeline_sources import SourceSelection

def pipeline_source(source: SourceInput) -> PipelineSource: ...
def pipeline_literal(value: Operand) -> PipelineExpr: ...
def pipeline_alias(name: Name) -> PipelineExpr: ...
def pipeline_col(table: Name, column: Name) -> PipelineExpr: ...
def pipeline_role(role: str, name: Name) -> PipelineExpr: ...
def pipeline_function(name: str, *arguments: Operand) -> PipelineExpr: ...
def pipeline_case(
    arms: list[tuple[Operand, Operand]] | tuple[tuple[Operand, Operand], ...],
    otherwise: Operand,
) -> PipelineExpr: ...
def pipeline_sources(name: str) -> SourceSelection: ...
