from typing import TypeAlias, Never
from ._native import Value, Identifier

Operand: TypeAlias = PipelineExpr | Value | None | bool | int | float | str
Name: TypeAlias = str | Identifier | PipelineExpr

class PipelineExpr:
    def __init__(self, _native_only: Never, /) -> None: ...
    def eq(self, /, value: Operand) -> PipelineExpr: ...
    def ne(self, /, value: Operand) -> PipelineExpr: ...
    def gt(self, /, value: Operand) -> PipelineExpr: ...
    def gte(self, /, value: Operand) -> PipelineExpr: ...
    def lt(self, /, value: Operand) -> PipelineExpr: ...
    def lte(self, /, value: Operand) -> PipelineExpr: ...
    def coalesce(self, /, value: Operand) -> PipelineExpr: ...
    def __eq__(self, value: object, /) -> PipelineExpr: ...  # type: ignore[override]
    def __ne__(self, value: object, /) -> PipelineExpr: ...  # type: ignore[override]
    def __gt__(self, value: Operand, /) -> PipelineExpr: ...
    def __ge__(self, value: Operand, /) -> PipelineExpr: ...
    def __lt__(self, value: Operand, /) -> PipelineExpr: ...
    def __le__(self, value: Operand, /) -> PipelineExpr: ...
    def __add__(self, value: Operand, /) -> PipelineExpr: ...
    def __sub__(self, value: Operand, /) -> PipelineExpr: ...
    def __mul__(self, value: Operand, /) -> PipelineExpr: ...
    def __truediv__(self, value: Operand, /) -> PipelineExpr: ...
    def __mod__(self, value: Operand, /) -> PipelineExpr: ...
    def __and__(self, value: Operand, /) -> PipelineExpr: ...
    def __or__(self, value: Operand, /) -> PipelineExpr: ...
    def __invert__(self, /) -> PipelineExpr: ...
    def __neg__(self, /) -> PipelineExpr: ...
    def asc(self, /) -> PipelineExpr: ...
    def desc(self, /) -> PipelineExpr: ...
    def is_null(self, /) -> PipelineExpr: ...
    def is_not_null(self, /) -> PipelineExpr: ...
    def as_(self, /, name: Name) -> PipelineExpr: ...
    def cast(self, /, kind: str) -> PipelineExpr: ...
    def in_array(self, /, values: list[Operand] | tuple[Operand, ...]) -> PipelineExpr: ...

class PipelineBinder:
    def __init__(self, _native_only: Never, /) -> None: ...
    def bind(self, /, value: object) -> PipelineExpr: ...

class PipelineOver:
    def __init__(self) -> None: ...
    def by(self, /, *keys: Operand) -> PipelineOver: ...
    def sort_by(self, /, *keys: Operand) -> PipelineOver: ...
    def rows(self, /, start: int | None = ..., end: int | None = ...) -> PipelineOver: ...
    def range(self, /, start: int | None = ..., end: int | None = ...) -> PipelineOver: ...
