from collections.abc import Awaitable
from typing import Any, Literal, TypeAlias
from ._native import Compiled, EntityModel
from .runtime import Connection

SourceRow: TypeAlias = tuple[EntityModel | None, ...]

class SourceSelection:
    @property
    def name(self) -> str: ...
    def describe(self) -> dict[str, Any]: ...

class SelectedSources:
    def inspect(
        self, *, terminal: Literal["all", "one", "one_opt"] = ...
    ) -> Compiled: ...
    def all(self, connection: Connection) -> Awaitable[list[SourceRow]]: ...
    def one(self, connection: Connection) -> Awaitable[SourceRow]: ...
    def one_opt(self, connection: Connection) -> Awaitable[SourceRow | None]: ...
