from .transactions import Transaction
from collections.abc import Awaitable
from typing import Any, Literal, TypeAlias, Never
from ._native import Compiled, EntityModel
from .runtime import Connection

SourceRow: TypeAlias = tuple[EntityModel | None, ...]

class SourceSelection:
    def __init__(self, _native_only: Never, /) -> None: ...
    @property
    def name(self) -> str: ...
    def describe(self, /) -> dict[str, Any]: ...

class SelectedSources:
    def __init__(self, _native_only: Never, /) -> None: ...
    def inspect(
        self, /, *, terminal: Literal["all", "one", "one_opt"] = ...
    ) -> Compiled: ...
    def all(self, /, connection: Connection | Transaction) -> Awaitable[list[SourceRow]]: ...
    def one(self, /, connection: Connection | Transaction) -> Awaitable[SourceRow]: ...
    def one_opt(self, /, connection: Connection | Transaction) -> Awaitable[SourceRow | None]: ...
