from collections.abc import Iterable, Iterator
from typing import Any, Generic, Literal, TypeAlias, TypeVar, final

T = TypeVar("T")

@final
class Range(Generic[T]):
    def __init__(self, lower: T | None = ..., upper: T | None = ..., bounds: str | None = ...) -> None: ...
    @staticmethod
    def empty() -> Range[Any]: ...
    @property
    def is_empty(self) -> bool: ...
    @property
    def lower(self) -> T | None: ...
    @property
    def upper(self) -> T | None: ...
    @property
    def bounds(self) -> str: ...
    @property
    def lower_inc(self) -> bool: ...
    @property
    def upper_inc(self) -> bool: ...
    @property
    def lower_inf(self) -> bool: ...
    @property
    def upper_inf(self) -> bool: ...
    def __eq__(self, value: object, /) -> bool: ...
    def __hash__(self, /) -> int: ...

@final
class Multirange(Generic[T]):
    def __init__(self, ranges: Iterable[Range[T]] | None = ...) -> None: ...
    def __len__(self, /) -> int: ...
    def __getitem__(self, key: int, /) -> Range[T]: ...
    def __iter__(self, /) -> Iterator[Range[T]]: ...
    def __eq__(self, value: object, /) -> bool: ...
    def __hash__(self, /) -> int: ...

RangeSubtype: TypeAlias = Literal["i16", "i32", "i64", "f32", "f64", "decimal", "text", "date", "time", "datetime", "datetime_utc", "uuid"]

@final
class CreatedRange:
    def __init__(self, name: str, subtype: RangeSubtype, *, schema: str | None = ...) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def schema(self) -> str | None: ...
    @property
    def subtype(self) -> str: ...
    def __eq__(self, value: object, /) -> bool: ...
    def __hash__(self, /) -> int: ...

@final
class CreatedMultirange:
    def __init__(self, name: str, subtype: RangeSubtype, *, schema: str | None = ...) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def schema(self) -> str | None: ...
    @property
    def subtype(self) -> str: ...
    def __eq__(self, value: object, /) -> bool: ...
    def __hash__(self, /) -> int: ...
