from collections.abc import Sequence
from typing import Any, Literal, TypeAlias
from ._native import Identifier, TypeName, Compiled
from ._expressions import Expr
from ._statements import Table
from ._entities import Entity

Name: TypeAlias = str | Identifier
BuiltinType: TypeAlias = Literal["char", "varchar", "text", "smallint", "integer", "bigint", "real", "double", "numeric", "boolean", "date", "time", "timestamp", "timestamptz", "interval", "bytea", "bit", "varbit", "money", "json", "jsonb", "uuid", "vector", "cidr", "inet", "macaddr", "ltree"]

class DataType:
    def __init__(self, kind: BuiltinType | TypeName, *, length: int | None = ..., precision: int | None = ..., scale: int | None = ...) -> None: ...
    def array(self) -> DataType: ...

class ColumnDef:
    def __init__(self, name: Name, kind: DataType | BuiltinType | TypeName) -> None: ...
    @property
    def name(self) -> str: ...
    def not_null(self) -> ColumnDef: ...
    def null(self) -> ColumnDef: ...
    def primary_key(self) -> ColumnDef: ...
    def unique(self) -> ColumnDef: ...
    def auto_increment(self) -> ColumnDef: ...
    def default(self, value: Any) -> ColumnDef: ...
    def check(self, condition: Expr) -> ColumnDef: ...
    def generated(self, expression: Expr) -> ColumnDef: ...

class DDL:
    def inspect(self) -> Compiled: ...

class CreateTable:
    def __init__(self, table: Table) -> None: ...
    def column(self, column: ColumnDef) -> CreateTable: ...
    def if_not_exists(self) -> CreateTable: ...
    def primary_key(self, first: Name, *rest: Name) -> CreateTable: ...
    def unique(self, first: Name, *rest: Name, name: Name | None = ..., nulls_not_distinct: bool = ...) -> CreateTable: ...
    def check(self, condition: Expr) -> CreateTable: ...
    def inspect(self) -> Compiled: ...

class CreateIndex:
    def __init__(self, table: Table, first: Name, *, name: Name | None = ...) -> None: ...
    def column(self, name: Name, *, descending: bool | None = ...) -> CreateIndex: ...
    def unique(self) -> CreateIndex: ...
    def nulls_not_distinct(self) -> CreateIndex: ...
    def if_not_exists(self) -> CreateIndex: ...
    def method(self, name: Literal["btree", "hash", "gin", "gist", "spgist", "brin"]) -> CreateIndex: ...
    def inspect(self) -> Compiled: ...

class EntitySchema:
    @property
    def table(self) -> CreateTable: ...
    @property
    def enums(self) -> list[DDL]: ...
    @property
    def indexes(self) -> list[CreateIndex]: ...
    @property
    def comments(self) -> list[DDL]: ...

def schema_from_entity(entity: Entity) -> EntitySchema: ...
def drop_table(table: Table, *, if_exists: bool = ..., cascade: bool = ...) -> DDL: ...
def rename_table(table: Table, name: Name) -> DDL: ...
def rename_column(table: Table, name: Name, new_name: Name) -> DDL: ...
def truncate(table: Table) -> DDL: ...
def add_column(table: Table, column: ColumnDef, *, if_not_exists: bool = ...) -> DDL: ...
def modify_column(table: Table, column: ColumnDef) -> DDL: ...
def drop_column(table: Table, name: Name) -> DDL: ...
def drop_index(table: Table, name: Name, *, if_exists: bool = ...) -> DDL: ...
def create_enum(name: Name | TypeName, values: Sequence[str]) -> DDL: ...
def add_enum_value(name: Name | TypeName, value: str, *, before: str | None = ..., after: str | None = ...) -> DDL: ...
def rename_enum_value(name: Name | TypeName, value: str, new_value: str) -> DDL: ...
def rename_enum(name: Name | TypeName, new_name: Name) -> DDL: ...
def drop_enum(name: Name | TypeName, *, if_exists: bool = ..., cascade: bool = ...) -> DDL: ...
