from typing import Literal
from ._schema import DDL, Name
from ._statements import Table

def add_not_null(table: Table, column: Name, *, name: Name | None = ..., no_inherit: bool = ..., not_valid: bool = ...) -> DDL: ...
def validate_constraint(table: Table, name: Name) -> DDL: ...
def alter_constraint(table: Table, name: Name, change: Literal["inherit", "no_inherit"]) -> DDL: ...
