from typing import ClassVar, Never
from ._expressions import Expr, Condition
from ._query_types import AliasedExpr, Compiled, Identifier, OrderBy

class Table:
    def __init__(self, name: str | Identifier, *, schema: str | Identifier | None = ...,
                 alias: str | Identifier | None = ...) -> None: ...
    def as_(self, /, alias: str | Identifier) -> Table: ...
    def col(self, /, name: str | Identifier) -> Expr: ...
    def star(self, /) -> Expr: ...
    @property
    def name(self) -> str: ...
    @property
    def schema(self) -> str | None: ...
    @property
    def alias(self) -> str | None: ...

class Join:
    def __init__(self, _native_only: Never, /) -> None: ...
    Inner: ClassVar[Join]
    Left: ClassVar[Join]
    Right: ClassVar[Join]
    Full: ClassVar[Join]

class Select:
    def __init__(self, *items: Expr | AliasedExpr) -> None: ...
    def select(self, /, *items: Expr | AliasedExpr) -> Select: ...
    def from_(self, /, table: Table) -> Select: ...
    def where_(self, /, predicate: Expr | Condition) -> Select: ...
    def join(self, /, table: Table, on: Expr | Condition, *, kind: Join = ...) -> Select: ...
    def cross_join(self, /, table: Table) -> Select: ...
    def group_by(self, /, *expressions: Expr) -> Select: ...
    def having(self, /, predicate: Expr | Condition) -> Select: ...
    def order_by(self, /, *orderings: OrderBy) -> Select: ...
    def limit(self, /, value: int | None) -> Select: ...
    def offset(self, /, value: int | None) -> Select: ...
    def distinct(self, /) -> Select: ...
    def inspect(self, /) -> Compiled: ...
