from typing import Any, ClassVar, Never
from collections.abc import Awaitable, Sequence
from ._native import Expr, Condition, Identifier
from ._entities import EntityColumn
from ._entity_models import EntityModel
from ._writes import Conflict, ConflictUpdate
from .runtime import Connection
from .transactions import Transaction

class Change:
    def __init__(self, _native_only: Never, /) -> None: ...
    @property
    def old(self) -> EntityModel: ...
    @property
    def new(self) -> EntityModel: ...

class Upserted:
    def __init__(self, _native_only: Never, /) -> None: ...
    def into_model(self, /) -> EntityModel: ...
    class Inserted(Upserted):
        __match_args__: ClassVar[tuple[str]]
        @property
        def model(self) -> EntityModel: ...
    class Updated(Upserted):
        __match_args__: ClassVar[tuple[str]]
        @property
        def change(self) -> Change: ...

class EntityUpdate:
    def __init__(self, _native_only: Never, /) -> None: ...
    def returning_change(self, /, connection: Connection | Transaction) -> Awaitable[Change]: ...

class EntityUpdateMany:
    def __init__(self, _native_only: Never, /) -> None: ...
    def set(self, /, column: str | Identifier | EntityColumn, value: Any) -> EntityUpdateMany: ...
    def filter(self, /, predicate: Expr | Condition) -> EntityUpdateMany: ...
    def returning_changes(self, /, connection: Connection | Transaction) -> Awaitable[list[Change]]: ...

class EntityInsert:
    def __init__(self, _native_only: Never, /) -> None: ...
    def on_conflict(self, /, action: Conflict | ConflictUpdate) -> EntityInsert: ...
    def returning_upsert(
        self, /, connection: Connection | Transaction
    ) -> Awaitable[Upserted.Inserted | Upserted.Updated | None]: ...

class EntityInsertMany:
    def __init__(self, _native_only: Never, /) -> None: ...
    def on_conflict(self, /, action: Conflict | ConflictUpdate) -> EntityInsertMany: ...
    def returning_upserts(
        self, /, connection: Connection | Transaction
    ) -> Awaitable[list[Upserted.Inserted | Upserted.Updated]]: ...
