from typing import Any, ClassVar, Never
from ._expressions import Expr
from ._query_types import Identifier, OrderBy

class FrameExclusion:
    def __init__(self, _native_only: Never, /) -> None: ...
    CurrentRow: ClassVar[FrameExclusion]
    Group: ClassVar[FrameExclusion]
    Ties: ClassVar[FrameExclusion]
    NoOthers: ClassVar[FrameExclusion]

class Frame:
    def __init__(self, _native_only: Never, /) -> None: ...
    def exclude(self, /, exclusion: FrameExclusion) -> Frame: ...

class FramePrecedingStart:
    def __init__(self, _native_only: Never, /) -> None: ...
    def and_preceding(self, /, offset: Any) -> Frame: ...
    def and_current_row(self, /) -> Frame: ...
    def and_following(self, /, offset: Any) -> Frame: ...
    def and_unbounded_following(self, /) -> Frame: ...
    def exclude(self, /, exclusion: FrameExclusion) -> Frame: ...

class FrameCurrentRowStart:
    def __init__(self, _native_only: Never, /) -> None: ...
    def and_current_row(self, /) -> Frame: ...
    def and_following(self, /, offset: Any) -> Frame: ...
    def and_unbounded_following(self, /) -> Frame: ...
    def exclude(self, /, exclusion: FrameExclusion) -> Frame: ...

class FrameFollowingStart:
    def __init__(self, _native_only: Never, /) -> None: ...
    def and_following(self, /, offset: Any) -> Frame: ...
    def and_unbounded_following(self, /) -> Frame: ...

class FrameType:
    def __init__(self, _native_only: Never, /) -> None: ...
    Range: ClassVar[FrameType]
    Rows: ClassVar[FrameType]
    Groups: ClassVar[FrameType]
    def unbounded_preceding(self, /) -> FramePrecedingStart: ...
    def preceding(self, /, offset: Any) -> FramePrecedingStart: ...
    def current_row(self, /) -> FrameCurrentRowStart: ...
    def following(self, /, offset: Any) -> FrameFollowingStart: ...

class Window:
    def __init__(self) -> None: ...
    def partition_by(self, /, *expressions: Expr) -> Window: ...
    def order_by(self, /, *orderings: OrderBy) -> Window: ...
    def frame(self, /, frame: Frame | FramePrecedingStart | FrameCurrentRowStart) -> Window: ...

class WindowedExpr:
    def __init__(self, _native_only: Never, /) -> None: ...
    def as_(self, /, alias: str | Identifier) -> WindowedExpr: ...

class WindowFunction:
    def __init__(self, _native_only: Never, /) -> None: ...
    def over(self, /, window: Window | str | Identifier) -> WindowedExpr: ...

def window_function(name: str, *arguments: Any) -> WindowFunction: ...
