from typing import Any
from ._expressions import Expr, Condition
from ._query_types import AliasedExpr, Compiled, Identifier
from ._statements import Table

class Conflict:
    @staticmethod
    def ignore() -> Conflict: ...

class ConflictTarget:
    def __init__(self, *columns: str | Identifier) -> None: ...
    def where_(self, predicate: Expr | Condition) -> ConflictTarget: ...
    def ignore(self) -> Conflict: ...
    def update(self, *columns: str | Identifier) -> ConflictUpdate: ...
    def set(self, column: str | Identifier, value: Any) -> ConflictUpdate: ...

class ConflictUpdate:
    def set(self, column: str | Identifier, value: Any) -> ConflictUpdate: ...
    def update(self, column: str | Identifier) -> ConflictUpdate: ...
    def where_(self, predicate: Expr | Condition) -> ConflictUpdate: ...

class Insert:
    def __init__(self, table: Table) -> None: ...
    def columns(self, *columns: str | Identifier) -> Insert: ...
    def values(self, *values: Any) -> Insert: ...
    def default_values(self) -> Insert: ...
    def on_conflict(self, action: Conflict | ConflictUpdate) -> Insert: ...
    def returning(self, *items: Expr | AliasedExpr) -> Insert: ...
    def inspect(self) -> Compiled: ...

class Update:
    def __init__(self, table: Table) -> None: ...
    def set(self, column: str | Identifier, value: Any) -> Update: ...
    def where_(self, predicate: Expr | Condition) -> Update: ...
    def all_rows(self) -> Update: ...
    def returning(self, *items: Expr | AliasedExpr) -> Update: ...
    def inspect(self) -> Compiled: ...

class Delete:
    def __init__(self, table: Table) -> None: ...
    def where_(self, predicate: Expr | Condition) -> Delete: ...
    def all_rows(self) -> Delete: ...
    def returning(self, *items: Expr | AliasedExpr) -> Delete: ...
    def inspect(self) -> Compiled: ...

class RawSQL:
    def __init__(self, template: str, values: list[Any] | tuple[Any, ...] | None = ...) -> None: ...
    @property
    def template(self) -> str: ...
    def inspect(self) -> Compiled: ...
    def inline_sql(self) -> str: ...
