[package]
name = "pgorm-migration"
version = "0.2.0"
authors = []
edition = "2024"
license = "MIT OR Apache-2.0"
rust-version = "1.88"
publish = false

[dependencies]
async-trait = { version = "0.1.92", default-features = false }
pgorm = { path = "..", features = ["macros"] }
# pgorm-cli = { path = "../pgorm/pgorm-cli", default-features = false, optional = true }
tracing = { version = "0.1.44", default-features = false, features = ["log"] }
tracing-subscriber = { version = "0.3.23", default-features = false, features = ["env-filter", "fmt"] }
futures = { version = "0.3.34", default-features = false, features = ["std"] }

[dev-dependencies]
dotenvy = "0.15.7"
tokio.workspace = true

[features]
default = []
