// The models the model and graph suites declare, and the schema they read:
// accounts with an identity key, a generated column, an enum and an array;
// posts that belong to an account, and an editor the server does not check;
// tags reached through a junction table; and versions keyed by two columns.

import { column, CreatedRange, model, Pool, TypeName } from "../lib/index.js";
import { scratchDatabase } from "./support.ts";

export const mood = new TypeName("mood", { schema: "app" });

export const Account = model("account", {
  schema: "app",
  columns: {
    id: column("i64", { primaryKey: true, generated: "byDefault" }),
    name: column("text"),
    displayName: column("text", { name: "display_name", nullable: true }),
    mood: column(mood, { nullable: true, values: ["calm", "glad", "sour"] }),
    tags: column("text", { array: true, default: true }),
    visits: column("i32", { default: true }),
    created: column("datetime_utc", { default: true }),
    span: column(new CreatedRange("floatrange", "f64", { schema: "app" }), { nullable: true }),
    seq: column("i32", { generated: "always" }),
  },
});

export const Post = model("post", {
  schema: "app",
  columns: {
    id: column("i64", { primaryKey: true }),
    authorId: column("i64", { name: "author_id" }),
    editorId: column("i64", { name: "editor_id", nullable: true }),
    title: column("text"),
  },
});

export const Tag = model("tag", { schema: "app", columns: { id: column("i32", { primaryKey: true }), label: column("text") } });

export const PostTag = model("post_tag", {
  schema: "app",
  columns: {
    postId: column("i64", { name: "post_id", primaryKey: true }),
    tagId: column("i32", { name: "tag_id", primaryKey: true }),
  },
});

export const Version = model("version", {
  schema: "app",
  columns: {
    doc: column("i32", { primaryKey: true }),
    rev: column("i32", { primaryKey: true }),
    body: column("text"),
  },
});

export const author = Post.belongsTo(Account, { from: "authorId", to: "id" });
export const editor = Post.belongsTo(Account, { from: "editorId", to: "id" });
export const posts = Account.hasMany(Post, { from: "id", to: "authorId" });
export const postTags = Post.hasMany(PostTag, { from: "id", to: "postId" });
export const tagOf = PostTag.belongsTo(Tag, { from: "tagId", to: "id" });

const SCHEMA = [
  "CREATE SCHEMA app",
  "CREATE TYPE app.mood AS ENUM ('calm', 'glad', 'sour', 'wild')",
  "CREATE TYPE app.floatrange AS RANGE (subtype = float8)",
  `CREATE TABLE app.account (
     id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     name text NOT NULL,
     display_name text,
     mood app.mood,
     tags text[] NOT NULL DEFAULT '{}',
     visits int4 NOT NULL DEFAULT 0,
     created timestamptz NOT NULL DEFAULT now(),
     span app.floatrange,
     seq int4 GENERATED ALWAYS AS (visits + 1) STORED
   )`,
  `CREATE TABLE app.post (
     id int8 PRIMARY KEY,
     author_id int8 NOT NULL REFERENCES app.account,
     editor_id int8,
     title text NOT NULL
   )`,
  "CREATE TABLE app.tag (id int4 PRIMARY KEY, label text NOT NULL)",
  "CREATE TABLE app.post_tag (post_id int8 REFERENCES app.post, tag_id int4 REFERENCES app.tag, PRIMARY KEY (post_id, tag_id))",
  "CREATE TABLE app.version (doc int4, rev int4, body text NOT NULL, PRIMARY KEY (doc, rev))",
];

/** A scratch database holding the schema, and a pool on it. */
export async function modelDatabase(prefix: string): Promise<{ pool: Pool; drop(): Promise<void> }> {
  const database = await scratchDatabase(prefix);
  const pool = new Pool(database.dsn, { maxSize: 4 });
  for (const sql of SCHEMA) await pool.execute(sql);
  return {
    pool,
    async drop() {
      await pool.close();
      await database.drop();
    },
  };
}

/** Empty every table, restarting the identity. */
export async function truncate(pool: Pool): Promise<void> {
  await pool.execute("TRUNCATE app.post_tag, app.tag, app.post, app.account, app.version RESTART IDENTITY");
}
