/**
 * Models JavaScript declares, and the reads and writes over them.
 *
 * @module
 */

// [spec:pgorm:req:napi.typing]
// [spec:pgorm:req:napi.models]

import type { Compiled, Condition, Expr, Operand, OrderBy, Predicate } from "./expressions.d.ts";
import type { Select, Table } from "./select.d.ts";
import type { Conflict, ConflictUpdate, Delete, Insert, Update } from "./writes.d.ts";
import type {
  Connection,
  CreatedMultirange,
  CreatedRange,
  Decimal,
  Interval,
  JsonValue,
  Multirange,
  OperationOptions,
  Pool,
  Queryable,
  Range,
  RowStream,
  ScalarKind,
  TypeName,
  Uuid,
  Value,
} from "./index.d.ts";
import type { Cursor, Graph, KeyInputs, Paginator } from "./graphs.d.ts";

/**
 * The kinds a model column declares: every kind a result decodes as. `u64`
 * and `char` are not among them, because no column decodes as either: an
 * `int8` reads as `i64` and a `bpchar` as `text`.
 */
export type ColumnKind = Exclude<ScalarKind, "u64" | "char"> | TypeName | CreatedRange | CreatedMultirange;

/** What a value of each scalar kind reads as. */
export interface KindValues {
  bool: boolean;
  i8: number;
  i16: number;
  i32: number;
  i64: bigint;
  u32: number;
  f32: number;
  f64: number;
  text: string;
  bytes: Uint8Array;
  json: JsonValue;
  decimal: Decimal;
  uuid: Uuid;
  date: Temporal.PlainDate;
  time: Temporal.PlainTime;
  datetime: Temporal.PlainDateTime;
  datetime_utc: Temporal.Instant;
  interval: Interval;
  ipnetwork: string;
  mac_address: Uint8Array;
  vector: Float32Array;
  int4range: Range<number>;
  int8range: Range<bigint>;
  numrange: Range<Decimal>;
  daterange: Range<Temporal.PlainDate>;
  tsrange: Range<Temporal.PlainDateTime>;
  tstzrange: Range<Temporal.Instant>;
  int4multirange: Multirange<number>;
  int8multirange: Multirange<bigint>;
  nummultirange: Multirange<Decimal>;
  datemultirange: Multirange<Temporal.PlainDate>;
  tsmultirange: Multirange<Temporal.PlainDateTime>;
  tstzmultirange: Multirange<Temporal.Instant>;
}

/** What a value of each kind is written as, where it takes more than it reads as. */
export interface KindInputs extends Omit<KindValues, "i64" | "interval"> {
  /** A `bigint`, or a `number` that is a safe integer. */
  i64: bigint | number;
  /** An `Interval`, or a `Temporal.Duration` converted as `Interval.from` converts it. */
  interval: Interval | Temporal.Duration;
}

/** What a created range's bound reads as, by its subtype. */
export interface SubtypeValues {
  i16: number;
  i32: number;
  i64: bigint;
  f32: number;
  f64: number;
  decimal: Decimal;
  text: string;
  date: Temporal.PlainDate;
  time: Temporal.PlainTime;
  datetime: Temporal.PlainDateTime;
  datetime_utc: Temporal.Instant;
  uuid: Uuid;
}

/** How a column is declared beside its kind. */
export interface ColumnOptions {
  /** The SQL column's name, when it is not the field's. */
  readonly name?: string;
  /** Whether it holds NULL; a nullable column may be left out of an insert. */
  readonly nullable?: boolean;
  /** Whether it is a one-dimensional array of its kind, whose items may be NULL. */
  readonly array?: boolean;
  /** Whether it is part of the primary key, which is every such column in declaration order. */
  readonly primaryKey?: boolean;
  /** Whether the table fills it when an insert leaves it out. */
  readonly default?: boolean;
  /**
   * Whether the server generates it: `"always"` for `GENERATED ALWAYS` —
   * identity or computed — which no write sets; `"byDefault"` for
   * `GENERATED BY DEFAULT AS IDENTITY`, which an insert may leave out.
   */
  readonly generated?: "always" | "byDefault";
  /** An enum column's labels, which every value it reads or writes is one of. */
  readonly values?: readonly string[];
}

declare const declared: unique symbol;

/**
 * A column's declaration, made by {@link column}: its kind, and how it is
 * declared beside it.
 */
export declare class Column<K extends ColumnKind = ColumnKind, O extends ColumnOptions = ColumnOptions> {
  private constructor();
  readonly kind: K;
  readonly name: string | null;
  readonly nullable: boolean;
  readonly array: boolean;
  readonly primaryKey: boolean;
  readonly default: boolean;
  readonly generated: "always" | "byDefault" | null;
  readonly values: readonly string[] | null;
  /** The options the column was declared with, as the types know them. */
  readonly [declared]?: O;
}

/**
 * Declare a column of `kind`: a kind's name such as `"i32"`, or a
 * schema-qualified `TypeName` for an enum or `CreatedRange` /
 * `CreatedMultirange` for a range type a schema created, as a decoded row
 * names each. An unknown option, `primaryKey` with `nullable`, a generated
 * column with a `default`, and `values` on a column that is no enum are
 * {@link ConstructionError}s.
 */
export declare function column<const K extends ColumnKind, const O extends ColumnOptions = {}>(
  kind: K,
  options?: O,
): Column<K, NoInfer<O>>;

type Labels<O> = O extends { readonly values: readonly (infer L extends string)[] } ? L : string;

/** What one value of a column of kind `K`, declared with `O`, reads as, before arrays and NULL. */
export type KindValue<K, O = {}> = K extends keyof KindValues ? KindValues[K]
  : K extends CreatedMultirange<infer S> ? Multirange<SubtypeValues[S]>
  : K extends CreatedRange<infer S> ? Range<SubtypeValues[S]>
  : K extends TypeName ? Labels<O>
  : never;

/** What one value of a column of kind `K` is written as, before arrays and NULL. */
export type KindInput<K, O = {}> = K extends keyof KindInputs ? KindInputs[K] : KindValue<K, O>;

type Arrayed<T, O> = O extends { readonly array: true } ? (T | null)[] : T;
type Nulled<T, O> = O extends { readonly nullable: true } ? T | null : T;

/** What a column's field reads as in a record. */
export type FieldValue<C> = C extends Column<infer K, infer O> ? Nulled<Arrayed<KindValue<K, O>, O>, O> : never;

/**
 * What a column's field is written as: a value of its kind, `null` where it
 * is nullable, a {@link Value} of its own kind, or an expression written as
 * it stands.
 */
export type FieldInput<C> = C extends Column<infer K, infer O>
  ? Nulled<Arrayed<KindInput<K, O>, O>, O> | Value | Expr
  : never;

/**
 * What a column is compared with: a value of its kind that a statement can
 * bind, a {@link Value} of its own kind, or an expression. A range is
 * compared as a `Value` naming its kind, and an interval not at all, as
 * built statements bind them.
 */
export type FieldOperand<C> = C extends Column<infer K, infer O>
  ? Extract<Arrayed<KindInput<K, O>, O>, Operand> | Value | Expr
  : never;

/** A model's columns by field. */
export type Columns = { readonly [field: string]: Column<any, any> };

/** A field of columns `C`. */
export type FieldOf<C> = keyof C & string;

type Flat<T> = { [K in keyof T]: T[K] } & {};

/** A record of columns `C`: each field's value, keyed by field. */
export type Row<C extends Columns> = { -readonly [F in keyof C]: FieldValue<C[F]> };

/** The columns of a model. */
export type ColumnsOf<M> = M extends Model<infer C> ? C : never;

/** A record of a model, as its reads decode it. */
export type RowOf<M> = Row<ColumnsOf<M>>;

type Optioned<C, Test> = { [F in keyof C]: C[F] extends Column<any, infer O> ? (O extends Test ? F : never) : never }[keyof C];

type GeneratedAlways<C> = Optioned<C, { readonly generated: "always" }>;
type Omissible<C> =
  | Optioned<C, { readonly nullable: true }>
  | Optioned<C, { readonly default: true }>
  | Optioned<C, { readonly generated: "byDefault" }>;
type PrimaryKey<C> = Optioned<C, { readonly primaryKey: true }>;

/**
 * An insert's row of a model: every field neither nullable, defaulted nor
 * generated, and any of those but the ones generated always.
 */
export type InsertOf<M> = M extends Model<infer C> ? Flat<
    & { [F in Exclude<keyof C, GeneratedAlways<C> | Omissible<C>>]: FieldInput<C[F]> }
    & { [F in Exclude<Omissible<C>, GeneratedAlways<C>>]?: FieldInput<C[F]> }
  >
  : never;

/** An update's assignments to a model: any fields but the ones generated always. */
export type UpdateOf<M> = M extends Model<infer C> ? { [F in Exclude<keyof C, GeneratedAlways<C>>]?: FieldInput<C[F]> }
  : never;

/** A model's primary key: each key field's value. */
export type KeyOf<M> = M extends Model<infer C> ? { [F in PrimaryKey<C>]: Exclude<FieldOperand<C[F]>, Expr> } : never;

/**
 * A model's column as an expression, qualified as its model's table is
 * named. A value it is compared with converts through the column's declared
 * kind — an enum's label is bound cast to its type — and an expression is
 * compared as written; comparing with `null` is a
 * {@link ConstructionError}, because it is never true: test with `isNull()`.
 */
export declare class ModelColumn<V = unknown, I extends Operand = Operand> extends Expr {
  /** The field, in the model's records. */
  readonly field: string;
  readonly column: Column;
  /** The type its field reads as, for the types alone. */
  readonly [declared]?: V;
  eq(other: I): Expr;
  ne(other: I): Expr;
  lt(other: I): Expr;
  lte(other: I): Expr;
  gt(other: I): Expr;
  gte(other: I): Expr;
  isDistinctFrom(other: I): Expr;
  isNotDistinctFrom(other: I): Expr;
  contains(other: I): Expr;
  containedBy(other: I): Expr;
  overlaps(other: I): Expr;
  isIn(source: readonly I[] | Select): Expr;
  isNotIn(source: readonly I[] | Select): Expr;
  between(lower: I, upper: I, options?: { readonly symmetric?: boolean }): Expr;
  notBetween(lower: I, upper: I, options?: { readonly symmetric?: boolean }): Expr;
}

/** The column expression of field `F` of columns `C`. */
export type ColumnOf<C extends Columns, F extends keyof C> = ModelColumn<FieldValue<C[F]>, FieldOperand<C[F]>>;

/** The fields of a relation's end: one, or a non-empty list paired in order. */
export type KeyFields<C> = FieldOf<C> | readonly [FieldOf<C>, ...FieldOf<C>[]];

/** The fields a relation pairs: `from` on the model it starts at, `to` on the other. */
export interface RelationKeys<From extends Model<any>, To extends Model<any>> {
  readonly from: KeyFields<ColumnsOf<From>>;
  readonly to: KeyFields<ColumnsOf<To>>;
}

/** A model's declaration as data. */
export interface ModelDescription {
  readonly schema: string | null;
  readonly table: string;
  readonly alias: string | null;
  readonly primaryKey: readonly string[];
  readonly fields: {
    readonly [field: string]: {
      readonly column: string;
      /** The kind as a result spells its columns' kinds: `i64`, `text[]`, `enum "app"."mood"`. */
      readonly kind: string;
      readonly nullable: boolean;
      readonly primaryKey: boolean;
      readonly default: boolean;
      readonly generated: "always" | "byDefault" | null;
      readonly values: readonly string[] | null;
    };
  };
}

/**
 * A model: a table and its columns' declarations, made by {@link model}.
 * Every method builds a new query or write over it; the model itself never
 * changes. Declaring one sends nothing and runs no DDL.
 */
export declare class Model<C extends Columns = Columns> {
  private constructor();
  /** The table's name. */
  readonly name: string;
  readonly schema: string | null;
  readonly alias: string | null;
  /** The table, schema-qualified and aliased as the model is. */
  readonly table: Table;
  /** Each field's column declaration. */
  readonly columns: C;
  /** The primary key's fields, in declaration order. */
  readonly primaryKey: readonly PrimaryKey<C>[];
  /** The same model read under `alias`, its columns qualified by it, as a self-join needs. */
  as(alias: string): Model<C>;
  /** A field's column, qualified as the model's table is named. */
  col<F extends FieldOf<C>>(field: F): ColumnOf<C, F>;
  /** The condition matching the row whose primary key this is: every key field, and no other. */
  key(values: KeyOf<Model<C>>): Condition;
  /** Every field of every row. */
  find(): ModelQuery<C, Row<C>>;
  /** The fields named, of every row. */
  select<const F extends FieldOf<C>>(...fields: [F, ...F[]]): ModelQuery<C, Pick<Row<C>, F>>;
  /** The row whose primary key this is. */
  findByKey(values: KeyOf<Model<C>>): ModelQuery<C, Row<C>>;
  /**
   * An INSERT of one row. A field left out takes the table's default; a
   * field the model declares neither nullable, defaulted nor generated must
   * be set, and one generated always cannot be.
   */
  insert(values: InsertOf<Model<C>>): ModelInsert<C>;
  /** An INSERT of rows that each set the same fields; no rows writes nothing and sends nothing. */
  insertMany(rows: readonly InsertOf<Model<C>>[]): ModelInsert<C>;
  /** An UPDATE of at least one field, which needs `where` or `allRows()` before it runs. */
  update(values: UpdateOf<Model<C>>): ModelUpdate<C>;
  /** A DELETE, which needs `where` or `allRows()` before it runs. */
  delete(): ModelDelete<C>;
  /** A relation from this model's foreign key to the key of `target`, which reads at most one row. */
  belongsTo<T extends Model<any>>(target: T, keys: RelationKeys<Model<C>, T>): Relation<Model<C>, T, "one">;
  /** A relation from this model's key to at most one row of `target`. */
  hasOne<T extends Model<any>>(target: T, keys: RelationKeys<Model<C>, T>): Relation<Model<C>, T, "one">;
  /** A relation from this model's key to any number of rows of `target`. */
  hasMany<T extends Model<any>>(target: T, keys: RelationKeys<Model<C>, T>): Relation<Model<C>, T, "many">;
  /** A graph rooted at this model, which decodes its records alone until a slot is joined. */
  graph(): Graph<[Model<C>], [Row<C>]>;
  describe(): ModelDescription;
}

/**
 * Declare a model of the table `name`, schema-qualified when `schema` is
 * given. A field is a key of `columns`, and its SQL column the column's
 * `name` or else the field; two fields of one column are a
 * {@link ConstructionError}.
 */
export declare function model<const C extends Columns>(
  name: string,
  declaration: { readonly schema?: string; readonly columns: C },
): Model<C>;

/** The options of a model query's join. */
export interface ModelJoinOptions {
  /** `"inner"`, the default, or `"left"`. */
  readonly kind?: "inner" | "left";
  /** The name the joined table answers to. */
  readonly alias?: string;
}

/**
 * A model's SELECT, made by its `find()`, `select(..)` or `findByKey(..)`.
 * Every method returns a new query, and the terminals decode each row into a
 * record `R`: a result whose columns are not the ones selected, whose kinds
 * are not the declared ones, or whose values break a declaration — a NULL
 * in a column not nullable, a label an enum column does not list — is a
 * {@link DecodeError}.
 */
export declare class ModelQuery<C extends Columns = Columns, R = Row<C>> {
  private constructor();
  /** The SELECT it runs. */
  readonly statement: Select;
  /** The SQL and values it runs, or with `"count"` the ones `count` runs. */
  inspect(terminal?: "count"): Compiled;
  /** Rows that also satisfy `predicate`. */
  where(predicate: Predicate): ModelQuery<C, R>;
  orderBy(...orderings: OrderBy[]): ModelQuery<C, R>;
  /** `null` removes it. */
  limit(count: number | bigint | null): ModelQuery<C, R>;
  offset(count: number | bigint | null): ModelQuery<C, R>;
  /**
   * Join the table at the far end of `relation` — from the query's model or
   * a table it joined — without reading its columns, as a condition on a
   * related row needs.
   */
  join(relation: Relation<any, any, any>, options?: ModelJoinOptions): ModelQuery<C, R>;
  all(db: Queryable, options?: OperationOptions): Promise<R[]>;
  /** Exactly one row; any other count is a {@link DecodeError}. */
  one(db: Queryable, options?: OperationOptions): Promise<R>;
  /** At most one row, or `null`; more is a {@link DecodeError}. */
  optional(db: Queryable, options?: OperationOptions): Promise<R | null>;
  /** The rows, one per pull, over a connection the stream holds until it ends. */
  stream(db: Pool | Connection, options?: OperationOptions): RowStream<R>;
  /** How many rows it reads, limit and offset aside. */
  count(db: Queryable, options?: OperationOptions): Promise<number>;
  /** A keyset cursor over the rows, ordered by `fields`. */
  cursor<const F extends readonly [FieldOf<C>, ...FieldOf<C>[]]>(...fields: F): Cursor<R, KeyInputs<C, F>>;
  /** Pages of `pageSize` rows. */
  paginate(pageSize: number): Paginator<R>;
}

/** A written row as it was before the write, and as the write left it. */
export interface Change<R> {
  readonly old: R;
  readonly new: R;
}

/**
 * What an upsert did with a row: inserted it, or updated the row its
 * conflict found, `new` being the row as the statement left it either way.
 */
export type Upserted<R> =
  | { readonly kind: "inserted"; readonly new: R }
  | { readonly kind: "updated"; readonly old: R; readonly new: R };

/** A write with a RETURNING list of a model's fields, whose terminals decode each returned row. */
export declare class ModelRows<R> {
  private constructor();
  readonly statement: Insert | Update | Delete;
  inspect(): Compiled;
  all(db: Queryable, options?: OperationOptions): Promise<R[]>;
  one(db: Queryable, options?: OperationOptions): Promise<R>;
  optional(db: Queryable, options?: OperationOptions): Promise<R | null>;
}

/** A model's INSERT. */
export declare class ModelInsert<C extends Columns = Columns> {
  private constructor();
  /** The INSERT it runs; an insert of no rows has none, and is a {@link ConstructionError} here. */
  readonly statement: Insert;
  /** The SQL and values it runs, or the ones an upsert terminal runs. */
  inspect(terminal?: "returningUpsert" | "returningUpserts"): Compiled;
  /** What a conflict does, the statement builders' `Conflict` naming SQL columns. */
  onConflict(action: Conflict | ConflictUpdate): ModelInsert<C>;
  /** The rows written, every field or the fields named. */
  returning(): ModelRows<Row<C>>;
  returning<const F extends FieldOf<C>>(...fields: [F, ...F[]]): ModelRows<Pick<Row<C>, F>>;
  /** The number of rows written. */
  execute(db: Queryable, options?: OperationOptions): Promise<number>;
  /** What the insert did with its one row, or `null` where its conflict clause wrote nothing. */
  returningUpsert(db: Queryable, options?: OperationOptions): Promise<Upserted<Row<C>> | null>;
  /** What the insert did with each row it wrote; a row its conflict clause held back is left out. */
  returningUpserts(db: Queryable, options?: OperationOptions): Promise<Upserted<Row<C>>[]>;
}

/** A model's UPDATE, which needs `where` or `allRows()` before it runs. */
export declare class ModelUpdate<C extends Columns = Columns> {
  private constructor();
  readonly statement: Update;
  /** The SQL and values it runs, or the ones a change terminal runs. */
  inspect(terminal?: "returningChange" | "returningChanges"): Compiled;
  /** Rows that also satisfy `predicate`. */
  where(predicate: Predicate): ModelUpdate<C>;
  /** Every row, said outright. */
  allRows(): ModelUpdate<C>;
  returning(): ModelRows<Row<C>>;
  returning<const F extends FieldOf<C>>(...fields: [F, ...F[]]): ModelRows<Pick<Row<C>, F>>;
  execute(db: Queryable, options?: OperationOptions): Promise<number>;
  /** The one row the update wrote, before and after; any other count is a {@link DecodeError}. */
  returningChange(db: Queryable, options?: OperationOptions): Promise<Change<Row<C>>>;
  /** Every row the update wrote, before and after. */
  returningChanges(db: Queryable, options?: OperationOptions): Promise<Change<Row<C>>[]>;
}

/** A model's DELETE, which needs `where` or `allRows()` before it runs. */
export declare class ModelDelete<C extends Columns = Columns> {
  private constructor();
  readonly statement: Delete;
  inspect(): Compiled;
  where(predicate: Predicate): ModelDelete<C>;
  allRows(): ModelDelete<C>;
  returning(): ModelRows<Row<C>>;
  returning<const F extends FieldOf<C>>(...fields: [F, ...F[]]): ModelRows<Pick<Row<C>, F>>;
  execute(db: Queryable, options?: OperationOptions): Promise<number>;
}

/**
 * A relation from one model to another, made by a model's `belongsTo`,
 * `hasOne` or `hasMany`: the fields of each end equal in a related pair of
 * rows, matched in order. A `"one"` relation reads at most one row at its
 * far end, a `"many"` relation any number.
 */
export declare class Relation<
  From extends Model<any> = Model<any>,
  To extends Model<any> = Model<any>,
  Card extends "one" | "many" = "one" | "many",
> {
  private constructor();
  readonly kind: "belongsTo" | "hasOne" | "hasMany";
  /** The model the relation starts at. */
  readonly from: From;
  /** The model at its far end. */
  readonly to: To;
  readonly fromFields: readonly string[];
  readonly toFields: readonly string[];
  readonly cardinality: Card;
  /** The rows at the far end related to `row`: none when one of its key fields is null. */
  find(row: Partial<RowOf<From>>): ModelQuery<ColumnsOf<To>, RowOf<To>>;
  /**
   * The rows at the far end of each of `rows`, read in one query: a list per
   * row for a `"many"` relation, otherwise a record per row, or `null` where
   * the row's key holds a NULL. A key nothing at the far end matches, or a
   * `hasOne` key two rows match, is a {@link DecodeError}.
   */
  load(
    db: Queryable,
    rows: readonly Partial<RowOf<From>>[],
    options?: OperationOptions,
  ): Promise<Card extends "many" ? RowOf<To>[][] : (RowOf<To> | null)[]>;
}
