// @ts-check

// A model's columns: each one's declared kind, nullability and key, what a
// value written to it or compared with it becomes, and the expression that
// reads it.
// [spec:pgorm:req:napi.models]

import { TRUSTED } from "./builder.js";
import { ConstructionError } from "./errors.js";
import { Expr } from "./expressions.js";
import { native } from "./operations.js";
import { Select } from "./select.js";
import { CreatedMultirange, CreatedRange, TypeName, Value } from "./values.js";

/** Marks a column made by `column()`. */
const DECLARED = Symbol("pgorm-napi column");

const OPTIONS = new Set(["name", "nullable", "array", "primaryKey", "default", "generated", "values"]);

/**
 * The kinds a result never decodes as, so a model column cannot declare
 * them: an `int8` reads as `i64`, and a `bpchar` as `text`.
 */
const UNDECODED = new Set(["u64", "char"]);

/** @type {(column: Column) => string} */
let keyOf;

/**
 * @param {unknown} flag
 * @param {string} what
 */
function flag(flag, what) {
  if (flag === undefined) return false;
  if (typeof flag !== "boolean") throw new ConstructionError(`a column's ${what} is a boolean`);
  return flag;
}

/**
 * @param {unknown} kind
 * @returns {kind is TypeName | CreatedRange | CreatedMultirange}
 */
function named(kind) {
  return kind instanceof TypeName || kind instanceof CreatedRange || kind instanceof CreatedMultirange;
}

/**
 * The labels an enum column takes, when it lists them.
 *
 * @param {unknown} values
 * @param {unknown} kind
 * @returns {readonly string[] | null}
 */
function labels(values, kind) {
  if (values === undefined) return null;
  if (!(kind instanceof TypeName)) throw new ConstructionError("only an enum column lists its values");
  if (!Array.isArray(values) || values.length === 0 || !values.every((label) => typeof label === "string")) {
    throw new ConstructionError("an enum column's values are a non-empty list of strings");
  }
  if (new Set(values).size !== values.length) throw new ConstructionError("an enum column lists each value once");
  return Object.freeze([...values]);
}

/**
 * A column's declaration: its kind, the SQL name it has when that is not the
 * field's, and whether it is nullable, an array, part of the primary key,
 * filled by a default or generated by the server. Made by {@link column}.
 */
export class Column {
  /** @type {string} */
  #key;

  /**
   * @param {unknown} kind
   * @param {unknown} options
   * @param {symbol} token
   */
  constructor(kind, options, token) {
    if (token !== DECLARED) throw new TypeError("a Column is made by column(kind, options)");
    if (typeof options !== "object" || options === null) throw new TypeError("a column's options are an object");
    for (const option of Object.keys(options)) {
      if (!OPTIONS.has(option)) throw new ConstructionError(`${JSON.stringify(option)} is no column option`);
    }
    const declared = /** @type {Record<string, unknown>} */ (options);
    if (typeof kind === "string") {
      if (UNDECODED.has(kind)) {
        throw new ConstructionError(`a result never decodes as ${kind}, so no model column declares it`);
      }
    } else if (named(kind)) {
      if (kind.schema === null) {
        throw new ConstructionError(
          "a model column of an enum or a created range names its type's schema, as a decoded row does",
        );
      }
    } else {
      throw new ConstructionError("a column's kind is a kind name, a TypeName, a CreatedRange or a CreatedMultirange");
    }
    /** @readonly */
    this.kind = kind;
    if (declared.name !== undefined && typeof declared.name !== "string") {
      throw new ConstructionError("a column's name is a string");
    }
    /** @readonly @type {string | null} */
    this.name = declared.name ?? null;
    /** @readonly */
    this.nullable = flag(declared.nullable, "nullable");
    /** @readonly */
    this.array = flag(declared.array, "array");
    /** @readonly */
    this.primaryKey = flag(declared.primaryKey, "primaryKey");
    /** @readonly */
    this.default = flag(declared.default, "default");
    const generated = declared.generated ?? null;
    if (generated !== null && generated !== "always" && generated !== "byDefault") {
      throw new ConstructionError('a column is generated "always" or "byDefault"');
    }
    /** @readonly @type {"always" | "byDefault" | null} */
    this.generated = generated;
    /** @readonly */
    this.values = labels(declared.values, kind);
    if (this.primaryKey && this.nullable) throw new ConstructionError("a primary-key column is not nullable");
    if (this.default && this.generated !== null) {
      throw new ConstructionError("a generated column has no default of its own: declare one or the other");
    }
    this.#key = native.modelKindKey(kind, this.array);
    Object.freeze(this);
  }

  static {
    keyOf = (column) => column.#key;
  }
}

/**
 * Declare a column of `kind`: a kind's name such as `"i32"`, a `TypeName`
 * for an enum or a `CreatedRange` / `CreatedMultirange`, each
 * schema-qualified as a decoded row names it.
 *
 * @param {unknown} kind
 * @param {unknown} [options]
 */
export function column(kind, options = {}) {
  return new Column(kind, options, DECLARED);
}

/**
 * The kind a column's values decode and bind as, spelled as a result spells
 * its columns' kinds.
 *
 * @param {Column} column
 */
export function columnKey(column) {
  return keyOf(column);
}

/**
 * What `input` becomes, written to `column` or compared with it: an
 * expression as written; a `Value` of the column's own kind; `null` as the
 * column's typed NULL where it is nullable; anything else converted to the
 * column's kind, exactly or not at all.
 *
 * @param {Column} column
 * @param {string} field
 * @param {unknown} input
 * @returns {Expr | Value}
 */
export function columnValue(column, field, input) {
  if (input instanceof Expr) return input;
  if (input === undefined) throw new ConstructionError(`${field} is undefined: leave it out, or pass null`);
  if (input instanceof Value) {
    const key = native.modelValueKey(input);
    if (key !== keyOf(column)) {
      throw new ConstructionError(`${field} is ${keyOf(column)}, and the Value given is ${key}`);
    }
    if (input.isNull && !column.nullable) throw new ConstructionError(`${field} is not nullable`);
    return input;
  }
  if (input === null) {
    if (!column.nullable) throw new ConstructionError(`${field} is not nullable`);
    return column.array ? Value.array(/** @type {any} */ (column.kind), null) : Value.null(/** @type {any} */ (column.kind));
  }
  if (column.values !== null) {
    const items = column.array && Array.isArray(input) ? input : [input];
    for (const item of items) {
      if (item !== null && !column.values.includes(/** @type {string} */ (item))) {
        throw new ConstructionError(`${JSON.stringify(item)} is not one of ${field}'s values`);
      }
    }
  }
  const kind = /** @type {any} */ (column.kind);
  if (column.array) {
    if (!Array.isArray(input)) throw new ConstructionError(`${field} is an array column`);
    return Value.array(kind, input);
  }
  return kind === "json" ? Value.json(/** @type {any} */ (input)) : new Value(input, kind);
}

/**
 * A model's column as an expression, qualified as the model's table is
 * named. A value it is compared with converts to the column's declared kind,
 * as pgorm's `ColumnTrait` comparisons cast through the column's type, so an
 * enum's label binds cast to its type; an expression is compared as written.
 */
export class ModelColumn extends Expr {
  /** @type {Column} */
  #column;
  /** @type {string} */
  #field;

  /**
   * @param {unknown} handle
   * @param {string} field
   * @param {Column} column
   * @param {symbol} token
   */
  constructor(handle, field, column, token) {
    super(handle, token === DECLARED ? TRUSTED : token);
    this.#column = column;
    this.#field = field;
  }

  /** The field the column is, in the model's records. */
  get field() {
    return this.#field;
  }

  /** The column's declaration. */
  get column() {
    return this.#column;
  }

  /** @param {unknown} value */
  #operand(value) {
    if (value === null) {
      throw new ConstructionError(`${this.#field} compared with null is never true: test it with isNull()`);
    }
    return columnValue(this.#column, this.#field, value);
  }

  /**
   * @override
   * @param {unknown} other
   */
  eq(other) {
    return super.eq(this.#operand(other));
  }

  /**
   * @override
   * @param {unknown} other
   */
  ne(other) {
    return super.ne(this.#operand(other));
  }

  /**
   * @override
   * @param {unknown} other
   */
  lt(other) {
    return super.lt(this.#operand(other));
  }

  /**
   * @override
   * @param {unknown} other
   */
  lte(other) {
    return super.lte(this.#operand(other));
  }

  /**
   * @override
   * @param {unknown} other
   */
  gt(other) {
    return super.gt(this.#operand(other));
  }

  /**
   * @override
   * @param {unknown} other
   */
  gte(other) {
    return super.gte(this.#operand(other));
  }

  /**
   * @override
   * @param {unknown} other
   */
  isDistinctFrom(other) {
    return super.isDistinctFrom(this.#operand(other));
  }

  /**
   * @override
   * @param {unknown} other
   */
  isNotDistinctFrom(other) {
    return super.isNotDistinctFrom(this.#operand(other));
  }

  /**
   * @override
   * @param {unknown} other
   */
  contains(other) {
    return super.contains(this.#operand(other));
  }

  /**
   * @override
   * @param {unknown} other
   */
  containedBy(other) {
    return super.containedBy(this.#operand(other));
  }

  /**
   * @override
   * @param {unknown} other
   */
  overlaps(other) {
    return super.overlaps(this.#operand(other));
  }

  /**
   * @override
   * @param {readonly unknown[] | Select} source
   */
  isIn(source) {
    return super.isIn(source instanceof Select ? source : this.#list(source));
  }

  /**
   * @override
   * @param {readonly unknown[] | Select} source
   */
  isNotIn(source) {
    return super.isNotIn(source instanceof Select ? source : this.#list(source));
  }

  /** @param {unknown} source */
  #list(source) {
    if (!Array.isArray(source)) throw new TypeError("isIn takes a list of values or a Select");
    return source.map((item) => this.#operand(item));
  }

  /**
   * @override
   * @param {unknown} lower
   * @param {unknown} upper
   * @param {{ symmetric?: boolean }} [options]
   */
  between(lower, upper, options) {
    return super.between(this.#operand(lower), this.#operand(upper), options);
  }

  /**
   * @override
   * @param {unknown} lower
   * @param {unknown} upper
   * @param {{ symmetric?: boolean }} [options]
   */
  notBetween(lower, upper, options) {
    return super.notBetween(this.#operand(lower), this.#operand(upper), options);
  }
}

/**
 * A model column's expression over `handle`, the native half of the column
 * reference its model's qualifier makes.
 *
 * @param {unknown} handle
 * @param {string} field
 * @param {Column} column
 */
export function modelColumn(handle, field, column) {
  return new ModelColumn(handle, field, column, DECLARED);
}
